Repository buddyboss/buddyboss-platform, pull requests merged in 2020-07, with the labels that each got.

#977 Warning and notices on Groups > Courses page
  src/bp-integrations/learndash/templates/buddypress/groups/single/courses-loop.php
Labels: bug, component: groups, learndash, status: needs review, status: needs testing

#1106 Update bp-core-avatars.php
  src/bp-core/bp-core-avatars.php
Labels: bug, php

#1091 #1090 Photos sent are not visible to the recipient
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: bug, component: media, component: messages, priority: high

#1111 BP Integration tab errors and notices with tabs
  src/bp-core/admin/bp-core-admin-functions.php
Labels: bug

#1114 Cannot delete conversation when Notification component is deactivated
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: Has-PR, bug, priority: medium, status: needs testing

#1115 "Post Update" button is freezing when we post long URL in the activities.
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-link-preview.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: bug, component: activity, priority: high, status: needs testing

#773 #772 Private Network doesn't work if you have custom registration page
  src/bp-core/bp-core-catchuri.php
Labels: QA Passed, bug, php, priority: medium, status: needs review

#1080 979 - fixed translate his/her/their determiners
  src/bp-members/bp-members-functions.php
  src/languages/buddyboss.pot
Labels: bug, component: profile fields, status: needs review

#1121 Cannot create or edit any posts
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
Labels: bug, priority: critical, status: needs testing

#978 Pending invites are gone once we scroll down the page.
  src/bp-templates/bp-nouveau/js/buddypress-group-invites.js
  src/bp-templates/bp-nouveau/js/buddypress-group-invites.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, component: groups, component: invites, javascript

#1123 #1049 fix translation
  src/bp-blogs/classes/class-bp-blogs-component.php
  src/bp-friends/classes/class-bp-friends-component.php
  src/bp-groups/classes/class-bp-groups-component.php
  src/bp-media/classes/class-bp-media-component.php
  src/bp-messages/classes/class-bp-messages-component.php
  src/bp-notifications/classes/class-bp-notifications-component.php
  src/languages/buddyboss.pot
Labels: bug, translation

#669 Fix options code and document
  src/bp-core/bp-core-options.php
Labels: bug, php, priority: low, status: needs review

#770 584 - Fixed the issue with top level domain characters more than 5
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: bug, priority: high, status: needs review

#1127 #1125 document text translation
  src/bp-document/bp-document-functions.php
  src/bp-templates/bp-nouveau/buddypress/document/activity-entry.php
  src/bp-templates/bp-nouveau/includes/document/functions.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: bug, component: document, status: needs review, translation

#1133 #1001 remove member and group type from admin menu
  src/bp-core/classes/class-bp-core.php
  src/bp-members/bp-members-functions.php
Labels: bug

#1140 Activity photo comment not working on email notification
  src/bp-activity/bp-activity-filters.php
  src/bp-core/classes/class-bp-email-tokens.php
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-loader.php
  src/bp-media/bp-media-filters.php
Labels: Email Template, bug, priority: medium, status: needs testing

#1093 Fix document and folder privacy
  src/bp-core/bp-core-template.php
  src/bp-document/bp-document-functions.php
  src/bp-document/bp-document-template.php
  src/bp-media/bp-media-filters.php
  src/bp-media/bp-media-functions.php
  src/bp-media/bp-media-template.php
  src/bp-messages/bp-messages-notifications.php
  src/bp-templates/bp-nouveau/buddypress/document/document-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/single-folder.php
  src/bp-templates/bp-nouveau/buddypress/media/actions.php
  src/bp-templates/bp-nouveau/buddypress/media/entry.php
  src/bp-templates/bp-nouveau/buddypress/media/single-album.php
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/document/ajax.php
  src/bp-templates/bp-nouveau/includes/document/functions.php
  src/bp-templates/bp-nouveau/includes/media/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/languages/buddyboss.pot
Labels: bug, component: document, component: groups, status: needs testing

#1070 #998 - allowing reordering the default gender in the profile fields
  src/bp-xprofile/admin/js/admin.js
  src/bp-xprofile/admin/js/admin.min.js
  src/bp-xprofile/bp-xprofile-admin.php
  src/bp-xprofile/classes/class-bp-xprofile-field-type-gender.php
Labels: QA Passed, bug, priority: medium, status: needs testing

#656 #641 - Repair and import tools are inaccessible when the platform is network activated
  src/bp-core/admin/bp-core-admin-functions.php
  src/bp-core/admin/js/settings-page.js
  src/bp-core/admin/js/settings-page.min.js
  src/bp-core/classes/class-bp-admin-tab.php
  src/bp-core/classes/class-bp-admin.php
  src/bp-forums/admin/functions.php
  src/bp-forums/admin/tools.php
  src/bp-media/bp-media-filters.php
  src/bp-xprofile/admin/js/admin.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, priority: high

#1132 German characters not translated on Activity preview
  src/bp-core/bp-core-functions.php
Labels: bug, component: activity, priority: medium, status: needs testing, translation

#1130 Issue with typing the email address in 'Post Update' on activity
  src/bp-core/js/mentions.js
  src/bp-core/js/mentions.min.js
  src/bp-groups/bp-groups-functions.php
Labels: bug, priority: medium, status: needs testing

#1128 Joining a group leads to 404
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
Labels: bug, component: groups, priority: medium, status: needs testing

#1151 #1144 Fix Group documents breadcrumb does not work when the documents page slug is not documents
  src/bp-document/bp-document-functions.php
Labels: bug, component: document, php, priority: medium

#714 bbp-single-topic shortcode is not working for subscribers.
  src/bp-forums/common/shortcodes.php
  src/bp-forums/forums/functions.php
  src/bp-forums/functions.php
  src/bp-forums/groups.php
  src/bp-forums/templates/default/bbpress/feedback-no-access-reply.php
  src/bp-forums/templates/default/bbpress/feedback-no-access-topic.php
  src/bp-forums/templates/default/extras/single-reply.php
  src/bp-forums/users/template.php
Labels: QA Passed, bug, status: needs testing

#1056 Profile completion widget is not updating when Object Caching is enabled
  src/bp-xprofile/classes/class-bp-xprofile-profile-completion-widget.php
Labels: QA Passed, bug, priority: medium

#509 Privacy issue - the user is still searchable with the fields set to "Only Me"
  src/bp-search/classes/class-bp-search-members.php
Labels: QA Passed, bug, component: search, priority: high

#1165 #1157 Fix sync wp and bp profile field first, last and nickname and display name
  src/bp-xprofile/bp-xprofile-functions.php
Labels: component: profile fields, php, priority: medium

#1166 #944 - Register screen, password should get an "eye" to toggle
  src/bp-templates/bp-nouveau/common-styles/_bp_registration.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/template-tags.php
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/languages/buddyboss.pot
Labels: status: changes requested

#877 873 - Added translation support for backend strings
  src/bp-core/admin/bp-core-admin-components.php
  src/bp-core/admin/bp-core-admin-pages.php
  src/bp-core/admin/settings/bp-admin-setting-general.php
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: changes requested

#1126 1059 - Fixed the translation issue
  src/bp-templates/bp-nouveau/includes/template-tags.php
  src/languages/buddyboss.pot
Labels: bug, component: profiles, priority: medium, status: needs review

#1175 Fixed : Group members can't see their hidden group when a group page …
  src/bp-groups/bp-groups-functions.php
Labels: bug, status: needs testing

#1182 Pagination issue after Profile Type filter on Member directory
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
Labels: bug, component: profiles, priority: medium, status: needs review, status: needs testing

#1193 Courses in Groups throwing error
  src/bp-integrations/learndash/templates/buddypress/groups/single/courses-loop.php
Labels: bug, component: groups, learndash, priority: medium

#1194 Private messaging not working when Members component page is non-english
  src/bp-templates/bp-nouveau/includes/messages/functions.php
Labels: bug, component: messages, priority: medium, status: needs review, status: needs testing

#1176 #935 - The footer of the reset email template is not centered.
  src/bp-templates/bp-nouveau/buddypress/assets/emails/wp/email-template.php
Labels: QA Passed, status: needs review

#902 898 - Fixed the JS issue with WP text editor in profile fields
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.js
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.min.js
Labels: QA Passed, bug, priority: medium

#841 Medium Editor > Image dragging not working
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, javascript, priority: critical

#368 "Heading" Profile search field issue
  src/bp-core/profile-search/bp-ps-admin.js
  src/bp-core/profile-search/bp-ps-admin.min.js
  src/bp-core/profile-search/bps-admin.php
  src/bp-core/profile-search/bps-form.php
  src/bp-templates/bp-nouveau/common-styles/_bp_members_loop.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: QA Passed, bug, component: profiles

#1183 Activate Page title issue when Rank Math Plugin is active
  src/bp-core/compatibility/bp-rankmath-plugin-helpers.php
Labels: bug, priority: medium, status: needs review

#1153 Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, Error when Popup Builder Plugin install with #1152
  src/bp-integrations/compatibility/bp-compatibility-integration.php
Labels: QA Passed, status: needs review

#1077 Fixed Document file rename does not allow characters from any language other than English
  src/bp-document/bp-document-functions.php
  src/bp-templates/bp-nouveau/buddypress/document/create-child-folder.php
  src/bp-templates/bp-nouveau/buddypress/document/create-folder.php
  src/bp-templates/bp-nouveau/buddypress/document/document-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/edit-child-folder.php
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/document/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, component: document, priority: medium

#921 880 - Fixed URL preview generation
  src/bp-activity/bp-activity-filters.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: bug, component: activity, priority: high

#1181 fix - When comment threading limit is reached there should still be a…
  src/bp-activity/bp-activity-template.php
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
Labels: QA Passed, bug, component: activity, php, priority: high, refactor

#1170 "reinstall emails" link brings me to "not allowed" page
  src/bp-core/admin/bp-core-admin-functions.php
Labels: QA Passed, bug, priority: medium

#1033 758 - allow to send group message without checking connection
  src/bp-messages/bp-messages-functions.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
Labels: QA Passed, bug, component: messages, priority: medium

#1011 1004 - Fixed the issue of send empty messages and extra spaces
  src/bp-forums/replies/functions.php
  src/bp-forums/topics/functions.php
  src/bp-templates/bp-nouveau/includes/activity/ajax.php
  src/bp-templates/bp-nouveau/includes/activity/functions.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: QA Passed, bug, component: messages, priority: medium

#1191 Quotes in discussion title are messed up in backend and produce informal quotes in frontend #1035
  src/bp-forums/topics/functions.php
Labels: QA Passed, status: needs review

#1192 Fix - Learndash changing the Edit page links in admin bar to homepage instead of groups page
  src/bp-integrations/learndash/bp-admin-learndash-tab.php
  src/bp-integrations/learndash/bp-learndash-filters.php
Labels: QA Passed, bug, component: groups, learndash, php, priority: critical

#889 The students can access the course group even after the expiration of the membership.
  src/bp-integrations/learndash/buddypress/Hooks.php
  src/bp-integrations/learndash/core/Admin.php
  src/bp-integrations/learndash/core/Dependencies.php
Labels: QA Passed, bug, component: groups, learndash, priority: high

#1219 #1218 - Styling issue of the "Reply" icon on User profile > Forum Replies page
  src/bp-forums/replies/template.php
  src/languages/buddyboss.pot
Labels: status: needs review

#1234 Updating sub-group information removed the sub-group from the parent group.
  src/bp-groups/bp-groups-functions.php
Labels: bug, component: groups, priority: high, status: needs review

#1034 Non-admin have HTML tags showing on forum replies
  src/bp-forums/common/formatting.php
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: bug, component: forums, priority: high, status: needs testing

#1164 Messages - improve the avatar display for multi-user message threads
  src/bp-integrations/learndash/core/Admin.php
  src/bp-messages/bp-messages-functions.php
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-thread.php
  src/bp-templates/bp-nouveau/common-styles/_bp_messages.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/languages/buddyboss.pot
Labels: QA Passed, feature: enhancement, priority: medium

#1247 Only Me option not working on Photo upload ( anyone can see that photo & also without login )
  src/bp-members/bp-members-filters.php
Labels: bug, component: media, priority: high, status: needs review

#1244 API updates and fixes
  src/bp-activity/classes/class-bp-rest-activity-comment-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-details-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-components-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-friends/classes/class-bp-rest-friends-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-invites/classes/class-bp-rest-invites-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-repeater-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: enhancement

#1254 loader file added filter if someone want to change anything
  src/bp-loader.php
Labels: Type: Support, feature: enhancement, status: needs review, status: needs testing

#1257 Multiple Repeater fields can not be deleted
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.js
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.min.js
  src/bp-xprofile/screens/edit.php
Labels: bug, component: profile fields, status: needs review

#1264 All Members option not working on Photo upload ( anyone can see that photo & also without login )
  src/bp-members/bp-members-filters.php
Labels: bug, component: media, priority: high, status: needs review

#1273 758 - Reopen fix for allow to send group message without checking connection
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: bug, component: messages, status: needs review

#1285 #480 fix notice
  src/bp-search/classes/class-bp-search.php
Labels: bug, component: search, php, status: needs review
