Repository buddyboss/buddyboss-platform, pull requests merged in 2020-05, with the labels that each got.

#776 #761 Server goes away when activate platform plugin with 60000 users
  src/bp-activity/bp-activity-functions.php
  src/bp-core/admin/bp-core-admin-tools.php
Labels: bug, component: activity, component: profiles, php, priority: critical, status: needs testing

#833 The Preview appearing twice after posting on activity feed.
  src/bp-core/classes/class-bp-embed.php
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
Labels: QA Passed, bug, component: activity, priority: critical

#844 #838 - Updates in Latest Activities widget is not showing properly
  package-lock.json
  src/bp-core/admin/css/common-rtl.css
  src/bp-core/admin/css/common.css
  src/bp-core/admin/css/customizer-controls-rtl.css
  src/bp-core/admin/css/customizer-controls.css
  src/bp-core/admin/css/hello-rtl.css
  src/bp-core/admin/css/hello.css
  src/bp-templates/bp-nouveau/buddypress/activity/widget.php
  src/bp-templates/bp-nouveau/common-styles/_bp_widgets.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: status: needs review

#865 Fixed - Text formatting option is overlapping with the media uploader
  src/bp-templates/bp-nouveau/common-styles/_bp_update_form.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: QA Passed, bug, priority: medium, status: needs review

#828 Lost Password link not working when WooCommerce plugin active
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-members/classes/class-bp-core-members-switching.php
Labels: bug

#890 Forums - when viewing another user's forum replies, it says "My Replies"
  src/bp-forums/classes/class-bp-forums-component.php
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: needs review

#893 Warning message with php 7.4
  src/bp-core/profile-search/bps-search.php
Labels: bug, priority: medium, status: needs review

#910 fix bp template stack filter array checked for null and empty and array
  src/bp-core/bp-core-template-loader.php
Labels: bug, php, priority: critical, status: needs review

#900 892 - fixed the pagination for topic shortcode
  src/bp-forums/topics/template.php
Labels: QA Passed, bug, priority: medium, status: needs review

#837 Dropzone error handling messages
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/languages/buddyboss.pot
Labels: bug, component: media, priority: medium, status: needs review, status: needs testing

#920 Apidoc fixes
  Gruntfile.js
  src/bp-forums/classes/class-bp-rest-reply-actions-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-actions-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-invites/classes/class-bp-rest-invites-endpoint.php
  src/bp-messages/classes/class-bp-messages-component.php
  src/bp-settings/classes/class-bp-rest-account-settings-endpoint.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-repeater-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-search-form-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-types-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-update-endpoint.php
  src/class-buddypress.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: bug, status: needs review

#886 859 - Fixed group user labels
  src/bp-groups/bp-groups-template.php
Labels: QA Passed, bug, priority: medium

#846 Fixed JS Error while deleting repeater field
  src/bp-groups/bp-groups-template.php
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.js
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, javascript, priority: medium

#887 885 - Fixed the forums page restrictions when there is no forums on site
  src/bp-core/bp-core-catchuri.php
Labels: QA Passed, bug, priority: medium, status: needs review

#853 Fixed Forums don't allow threaded discussions beyond one level deep
  src/bp-forums/users/template.php
Labels: QA Passed, bug, php, priority: medium, status: needs review

#852 850 - Fixed the JS error for memberpress stripe credit card field
  src/bp-core/js/register.js
  src/bp-core/js/register.min.js
Labels: bug, priority: medium, status: needs review

#831 Can not translate 'Send Message' button on 'Groups > message' page.
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages.php
Labels: bug, component: groups, status: needs review

#851 Fixed Email not sent to User after changing Password or Email
  src/bp-core/bp-core-wp-emails.php
  src/bp-xprofile/bp-xprofile-filters.php
Labels: QA Passed, bug, php, priority: medium, status: needs review

#863 862 - Fixed the PHP warning and notices
  src/bp-templates/bp-nouveau/buddypress/search/loop/topic-ajax.php
  src/bp-templates/bp-nouveau/buddypress/search/loop/topic.php
Labels: bug, priority: medium, status: needs review, status: needs testing

#720 Disallow Nickname visibility to be changed on frontend instead of Fir…
  src/bp-xprofile/bp-xprofile-caps.php
Labels: bug, component: profile fields, component: profiles, status: needs review

#664 #519 - Privacy issue with nick name
  src/bp-templates/bp-nouveau/buddypress/members/single/cover-image-header.php
Labels: bug, priority: high, status: needs review

#727 Hidden groups unavailable for Learndash group sync with Social group.
  src/bp-integrations/learndash/buddypress/Group.php
Labels: bug, status: needs review

#894 872 - Added suggested label when user search for a blank string
  src/bp-templates/bp-nouveau/buddypress/search/results-page.php
  src/languages/buddyboss.pot
Labels: bug, priority: low, status: changes requested
