Repository buddyboss/buddyboss-platform, pull requests merged in 2020-02, with the labels that each got.

#560 LifterLMS Network Search
  src/bp-core/images/search/course-content.svg
  src/bp-core/images/search/quiz.svg
  src/bp-search/bp-search-functions.php
  src/languages/buddyboss.pot
Labels: lifterlms, priority: low, status: needs review

#570 Validation is showing before successful registration.
  src/bp-core/js/register.js
  src/bp-core/js/register.min.js
Labels: bug, priority: critical, status: needs review

#571 Fix activity mentions tab goes to fatal error
  src/bp-activity/bp-activity-notifications.php
Labels: bug, component: activity, priority: critical, status: needs review

#578 Can not translate 'Send' and 'Cancel' button on Groups -> Send Invites page.
  src/bp-templates/bp-nouveau/buddypress/groups/single/invite/send-invites.php
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: needs review

#548 Wrong link in message notification when LearnDash is activated with WPML
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: bug, priority: high, status: needs review

#582 When 'Post formatting' is unselected in forum settings, the forum reply pop up doesn't work.
  src/bp-forums/templates/default/bbpress-functions.php
Labels: bug, status: needs review

#591 New Discussion modal window not working & TranslatePress select2 fix
  src/bp-core/bp-core-cssjs.php
  src/bp-forums/templates/default/js/common.js
  src/bp-templates/bp-nouveau/js/buddypress-group-invites.js
  src/bp-templates/bp-nouveau/js/buddypress-group-invites.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: Has-PR, bug, component: forums, priority: high, status: needs review, status: needs testing

#598 #572 - fix line embeds for activity
  src/bp-core/classes/class-bp-embed.php
Labels: bug, component: activity, priority: high, status: needs review

#600 Email Invite's last sentence can not be translated.
  src/bp-invites/actions/invites.php
  src/languages/buddyboss.pot
Labels: bug, component: invites, status: needs review, translation

#545 Giphy search is not working on forums/discussion pages
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: bug, priority: critical, status: needs review

#490 Unable to Translate Strings within JavaScript Files (2)
  src/bp-core/bp-core-cssjs.php
  src/bp-core/js/vendor/dropzone.js
  src/bp-core/js/vendor/dropzone.min.js
  src/languages/buddyboss.pot
Labels: bug, component: activity, priority: high

#338 T1805: Issue: Video embed not working when a text is added in replies of forum discussions - #57224
  src/bp-forums/replies/functions.php
  src/bp-forums/topics/functions.php
Labels: bug, component: forums

#552 Group Names with & symbol displays html equivalent &amp;
  src/bp-templates/bp-nouveau/includes/groups/functions.php
Labels: bug, priority: high, status: needs review
