Repository buddyboss/buddyboss-platform, pull requests merged in 2020-08, with the labels that each got.

#1267 added a visual setting for max upload size for media and documents
  src/bp-core/bp-core-functions.php
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-functions.php
  src/bp-media/bp-media-settings.php
  src/bp-templates/bp-nouveau/includes/document/functions.php
  src/bp-templates/bp-nouveau/includes/media/functions.php
Labels: component: document, component: media, feature: enhancement, status: needs testing

#1222 Media popup on elementor activity widget
  src/bp-templates/bp-nouveau/buddypress/media/theatre.php
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: bug, component: activity, elementor, priority: medium

#1328 Document code refactor for api
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-document/classes/class-bp-document-folder.php
  src/bp-document/classes/class-bp-document.php
  tests/phpunit/includes/install.php
Labels: feature: enhancement, refactor

#1284 GIFs are not removed when post deleted from front end
  src/bp-media/bp-media-filters.php
Labels: QA Passed, bug, priority: medium

#1334 The "Read More" button is missing for long comments on Activity post
  src/bp-activity/bp-activity-filters.php
Labels: bug, priority: high, status: needs review

#1340 Elementor - Platform changes
  src/bp-core/bp-core-functions.php
  src/bp-xprofile/bp-xprofile-filters.php
  src/bp-xprofile/bp-xprofile-functions.php
  src/bp-xprofile/classes/class-bp-xprofile-profile-completion-widget.php
Labels: QA Passed, component: profiles, refactor

#1349 Profile completion widget not updating while having a repeater fields
  src/bp-xprofile/bp-xprofile-functions.php
Labels: bug, priority: medium, status: needs review

#1366 Private messages are deleted as soon as you click on the send button
  src/bp-messages/classes/class-bp-messages-message.php
Labels: bug, component: messages, priority: high, status: needs review

#1333 Elementor plugin not working when we set BP pages as front page
  src/bp-core/bp-core-catchuri.php
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: QA Passed, bug, priority: critical, status: needs review

#1304 #1303 fix mesage count issue
  src/bp-messages/bp-messages-filters.php
  src/bp-messages/classes/class-bp-messages-thread.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: QA Passed, bug, component: messages

#1265 Fixed Document tab layout issue
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: QA Passed, bug, priority: medium

#1364 Rest API Fixes
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/trait-attachments.php
  src/bp-forums/classes/class-bp-rest-forums-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
  src/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-invites/classes/class-bp-rest-invites-endpoint.php
  src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php
  src/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: bug, priority: medium, status: needs review

#1338 Auto generate preview link after insert Emoji and enter new link
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: bug, priority: medium, status: needs review

#588 Fixed Some UI issues on Album page
  src/bp-templates/bp-nouveau/buddypress/media/single-album.php
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: needs review

#1134 Text formatting editor issues
  src/bp-forums/templates/default/js/common.js
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, priority: medium

#1280 #1278 Fix - LearnDash Group Memberships - BB Platform conflict
  src/bp-integrations/learndash/buddypress/Hooks.php
  src/bp-integrations/learndash/buddypress/Sync.php
  src/bp-integrations/learndash/library/SyncGenerator.php
  src/bp-integrations/learndash/templates/buddypress/groups/single/courses-content-display.php
  src/bp-integrations/learndash/templates/buddypress/groups/single/courses-courses.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/languages/buddyboss.pot
Labels: bug, component: groups, learndash, php, priority: critical

#1266 Activity date translation in activity feed not working on Translatepress #1216
  src/bp-core/bp-core-functions.php
Labels: status: needs review, status: needs testing

#861 Notifications on nested replies in discussion bug
  src/bp-forums/notifications.php
Labels: bug, component: forums, component: notifications, status: in progress

#1387 #1386 fix subfolder download issues
  src/bp-templates/bp-nouveau/includes/document/functions.php
Labels: QA Passed, bug, component: document

#1405 Document/Folder have a privacy All Members are Downloadable without login
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-functions.php
Labels: bug, component: document, component: media, priority: high

#1410 Fix - duplicate filter issues
  src/bp-document/bp-document-functions.php
Labels: bug, component: document, priority: medium

#1241 Profile menu hide changes
  src/bp-core/classes/class-bp-core-nav.php
  src/bp-templates/bp-nouveau/common-styles/_bp_forms.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/customizer-controls.php
  src/bp-templates/bp-nouveau/includes/customizer.php
  src/bp-templates/bp-nouveau/includes/functions.php
  src/bp-templates/bp-nouveau/js/customizer.js
  src/bp-templates/bp-nouveau/js/customizer.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, component: groups, component: profiles, feature: enhancement

#1174 #1055 profile dropdown backend menu changes
  src/bp-core/admin/bp-core-admin-functions.php
  src/bp-core/bp-core-adminbar.php
  src/bp-core/bp-core-filters.php
  src/bp-core/bp-core-functions.php
  src/bp-core/classes/class-bp-walker-nav-menu-checklist.php
  src/bp-forums/classes/class-bp-forums-component.php
  src/bp-xprofile/classes/class-bp-xprofile-component.php
Labels: QA Passed, component: groups, component: profiles, feature: enhancement
