Repository buddyboss/buddyboss-platform, pull requests merged in 2020-12, with the labels that each got.

#1820 Fixed DOMDocument class not found fatal error
  src/bp-integrations/compatibility/bp-compatibility-integration.php
Labels: status: needs review

#1857 Added video mime type checker in settings > media > video
  src/bp-core/admin/templates/check-video-mime-type.php
  src/bp-core/classes/class-bp-admin.php
Labels: status: needs review

#1869 #1868 - Fix - Lack of Capability Check on Profile Page
  src/bp-xprofile/bp-xprofile-filters.php
Labels: bug, component: profile fields, component: profiles, status: needs review

#1865 BB REST API - Activity Endpoint : Relevant Feed
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-document/classes/class-bp-rest-document-folder-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-rest-signup-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: enhancement, priority: medium

#1874 Video uploading activity
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
  src/bp-video/bp-video-filters.php
  src/languages/buddyboss.pot
Labels: status: needs review

#1883 Video upload in group message
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages.php
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/languages/buddyboss.pot
Labels: status: needs review

#1894 Added Video Upload in forum
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/js/buddypress-media.js
Labels: status: needs review

#1129 Enhancement: Media and Documents
  src/bp-activity/bp-activity-filters.php
  src/bp-activity/bp-activity-template.php
  src/bp-core/bp-core-template.php
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-forums/templates/default/bbpress-functions.php
  src/bp-media/bp-media-filters.php
  src/bp-media/bp-media-functions.php
  src/bp-media/bp-media-settings.php
  src/bp-media/bp-media-template.php
  src/bp-media/classes/class-bp-media-album.php
  src/bp-templates/bp-nouveau/buddypress/document/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/document-create-folder.php
  src/bp-templates/bp-nouveau/buddypress/document/document-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/document-loop.php
  src/bp-templates/bp-nouveau/buddypress/document/document-uploader.php
  src/bp-templates/bp-nouveau/buddypress/document/location-move.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/photos.php
  src/bp-templates/bp-nouveau/buddypress/media/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/media/add-media.php
  src/bp-templates/bp-nouveau/buddypress/media/album-entry.php
  src/bp-templates/bp-nouveau/buddypress/media/albums.php
  src/bp-templates/bp-nouveau/buddypress/media/create-album.php
  src/bp-templates/bp-nouveau/buddypress/media/entry.php
  src/bp-templates/bp-nouveau/buddypress/media/index.php
  src/bp-templates/bp-nouveau/buddypress/media/location-move.php
  src/bp-templates/bp-nouveau/buddypress/media/media-create-album.php
  src/bp-templates/bp-nouveau/buddypress/media/media-loop.php
  src/bp-templates/bp-nouveau/buddypress/media/media-move.php
  src/bp-templates/bp-nouveau/buddypress/media/media-privacy.php
  src/bp-templates/bp-nouveau/buddypress/media/uploader.php
  src/bp-templates/bp-nouveau/buddypress/members/single/media.php
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_dropzone.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/icons/bb-icons.css
  src/bp-templates/bp-nouveau/icons/bb-icons.eot
  src/bp-templates/bp-nouveau/icons/bb-icons.min.css
  src/bp-templates/bp-nouveau/icons/bb-icons.svg
  src/bp-templates/bp-nouveau/icons/bb-icons.ttf
  src/bp-templates/bp-nouveau/icons/bb-icons.woff
  src/bp-templates/bp-nouveau/icons/bb-icons.woff2
  src/bp-templates/bp-nouveau/icons/config.json
  src/bp-templates/bp-nouveau/includes/document/ajax.php
  src/bp-templates/bp-nouveau/includes/document/functions.php
  src/bp-templates/bp-nouveau/includes/media/ajax.php
  src/bp-templates/bp-nouveau/includes/media/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, component: document, component: media, feature: enhancement, status: ready for release

#1838 Message Query Enhancement
  src/bp-messages/bp-messages-functions.php
  src/bp-messages/classes/class-bp-messages-message.php
  src/bp-messages/classes/class-bp-messages-notice.php
  src/bp-messages/classes/class-bp-messages-thread.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: bug, component: messages, feature: enhancement, php, refactor, status: ready for release

#1901 Fix - Remove move in all media/documents for admin
  src/bp-templates/bp-nouveau/buddypress/document/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/document-entry.php
  src/bp-templates/bp-nouveau/buddypress/media/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/media/entry.php
Labels: bug, component: document, component: media

#1907 Fixed Photo move issue
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: Merged in Dev - RFT, bug, priority: high, status: needs review, status: ready for release

#1911 Fix media and document id meta for activity
  src/bp-activity/bp-activity-filters.php
  src/bp-document/classes/class-bp-document.php
  src/bp-media/classes/class-bp-media.php
Labels: component: activity, component: document, component: media, priority: critical, status: needs review

#1916 Fix Media/Document Move
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-functions.php
Labels: Merged in Dev - RFT, bug, component: document, component: media, status: needs review, status: ready for release

#1888 #823 - Implement videoJs player
  src/bp-core/bp-core-cssjs.php
  src/bp-core/css/vendor/video-js.css
  src/bp-core/css/vendor/video-js.min.css
  src/bp-core/js/vendor/video.js
  src/bp-core/js/vendor/video.min.js
  src/bp-templates/bp-nouveau/buddypress/video/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/video/entry.php
  src/bp-templates/bp-nouveau/buddypress/video/single-video.php
  src/bp-templates/bp-nouveau/buddypress/video/theatre.php
  src/bp-templates/bp-nouveau/includes/video/ajax.php
  src/bp-templates/bp-nouveau/includes/video/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
  src/bp-video/bp-video-template.php
  src/bp-video/classes/class-bp-video.php
  src/languages/buddyboss.pot
Labels: component: media, feature: enhancement, feature: major, priority: medium, status: in progress

#1797 HTML tags are showing in the forums when subscribers post copy-paste content from an external DOCS to forums
  src/bp-core/js/vendor/medium-editor.js
  src/bp-core/js/vendor/medium-editor.min.js
  src/bp-forums/common/formatting.php
  src/bp-forums/core/filters.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#1855 Only hidden groups in the site other group members single activity not accessible by other members
  src/bp-groups/bp-groups-activity.php
  src/bp-groups/classes/class-bp-groups-group.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: activity, component: groups, priority: medium, status: ready for release

#1922 #1900 fixed Member loading on scroll issue
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, status: ready for release

#1792 Validate the GET value so it should not generate the php error
  src/bp-members/classes/class-bp-core-members-switching.php
Labels: QA Passed, bug, priority: medium, status: ready for release

#814 781 - Fixed the forum auto suggest on forum archive page
  src/bp-search/classes/class-bp-search-bbpress-forums-replies.php
  src/bp-search/classes/class-bp-search-bbpress-forums-topics.php
  src/bp-search/classes/class-bp-search-bbpress-forums.php
  src/bp-search/classes/class-bp-search.php
  src/bp-templates/bp-nouveau/includes/search/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-search.js
  src/bp-templates/bp-nouveau/js/buddypress-search.min.js
Labels: Merged in Dev - RFT, QA Passed, bug, component: forums, priority: high, priority: medium

#1580 #1538 - Fixed the RTL issue with the code editor for the RTL languages
  src/bp-templates/bp-nouveau/common-styles/_codemirror.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high

#1943 API Enhancement - Media/Documents + Message Query
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-document/classes/class-bp-rest-document-details-endpoint.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: enhancement, status: needs review

#1881 Feature Webinar
  src/languages/buddyboss.pot
Labels: feature: major, status: needs review

#1955 Fixed moderation email button styling
  src/bp-core/bp-core-functions.php
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: needs review

#1953 Fix user activity friends scope
  src/bp-friends/bp-friends-activity.php
Labels: QA Passed, bug, component: activity, status: ready for release

#1954 Moderation API
  Gruntfile.js
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-forums/classes/class-bp-rest-bbp-walker-reply.php
  src/bp-forums/classes/class-bp-rest-forums-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-actions-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-moderation/classes/class-bp-moderation-component.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-report-endpoint.php
  src/class-buddypress.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: major, status: needs review

#1963 Fixed Moderation popup height issue
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: bug, status: needs review

#1968 Fixing report icon and block a member popup on message screen styling
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-single-header.php
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/icons/bb-icons.css
  src/bp-templates/bp-nouveau/icons/bb-icons.eot
  src/bp-templates/bp-nouveau/icons/bb-icons.min.css
  src/bp-templates/bp-nouveau/icons/bb-icons.svg
  src/bp-templates/bp-nouveau/icons/bb-icons.ttf
  src/bp-templates/bp-nouveau/icons/bb-icons.woff
  src/bp-templates/bp-nouveau/icons/bb-icons.woff2
  src/bp-templates/bp-nouveau/icons/config.json
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: needs review

#1973 Video preview in documents
  src/bp-document/bp-document-template.php
  src/bp-templates/bp-nouveau/buddypress/document/document-entry.php
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/document/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/languages/buddyboss.pot
Labels: status: needs review

#1974 #Issue 1900 Loading issue fixed
  src/bp-templates/bp-nouveau/common-styles/_bp_groups_messages.scss
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
Labels: status: needs testing
