Repository buddyboss/buddyboss-platform, pull requests merged in 2021-04, with the labels that each got.

#2297 Refector/video symlink image sizes
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-functions.php
  src/bp-templates/bp-nouveau/includes/document/ajax.php
Labels: feature: enhancement, refactor

#2322 Update bp-groups-admin.php
  src/bp-groups/bp-groups-admin.php
Labels: bug, component: groups, component: media, php

#2288 Fix typo
  src/bp-core/gdpr/class-bp-group-export.php
Labels: bug, typo

#2349 Fixed db error with column not found.
  src/bp-core/bp-core-filters.php
Labels: Merged in Dev - RFT, priority: high, status: ready for release

#2358 API Fixes and Enhancement
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-media/classes/class-bp-rest-media-details-endpoint.php
  src/bp-members/classes/class-bp-rest-signup-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-performance/classes/class-helper.php
  src/bp-performance/classes/class-option-clear-cache.php
  src/bp-performance/classes/class-performance.php
  src/bp-performance/classes/class-settings.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: bug

#2367 API and Performance fixes
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-performance/classes/class-cache.php
  src/bp-performance/classes/integrations/class-integration-abstract.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-update-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: enhancement

#2368 Add Legal Agreement checkbox to Register Form
  src/bp-core/admin/bp-core-admin-pages.php
  src/bp-core/admin/bp-core-admin-settings.php
  src/bp-core/admin/js/settings-page.js
  src/bp-core/admin/js/settings-page.min.js
  src/bp-core/admin/settings/bp-admin-setting-general.php
  src/bp-core/bp-core-catchuri.php
  src/bp-core/bp-core-options.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-members/classes/class-bp-rest-signup-endpoint.php
  src/bp-members/screens/register.php
  src/bp-templates/bp-nouveau/common-styles/_bp_magnific.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/template-tags.php
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/endpoints/api_project.js
  src/endpoints/api_project.json
  src/languages/buddyboss.pot
Labels: feature: enhancement, priority: high
