Repository buddyboss/buddyboss-platform, pull requests merged in 2021-11, with the labels that each got.

#3091 fix/3090 - Add/fix object caching for dozens of objects, reducing redundant queries significantly
  src/bp-activity/bp-activity-cache.php
  src/bp-activity/bp-activity-functions.php
  src/bp-activity/classes/class-bp-activity-activity.php
  src/bp-blogs/bp-blogs-cache.php
  src/bp-blogs/classes/class-bp-blogs-blog.php
  src/bp-blogs/classes/class-bp-blogs-component.php
  src/bp-core/bp-core-functions.php
  src/bp-core/classes/class-bp-core.php
  src/bp-document/bp-document-cache.php
  src/bp-document/bp-document-functions.php
  src/bp-forums/classes/class-bp-forums-component.php
  src/bp-friends/bp-friends-cache.php
  src/bp-friends/bp-friends-template.php
  src/bp-friends/classes/class-bp-friends-friendship.php
  src/bp-groups/bp-groups-cache.php
  src/bp-groups/classes/class-bp-groups-component.php
  src/bp-groups/classes/class-bp-groups-group.php
  src/bp-groups/classes/class-bp-groups-member.php
  src/bp-integrations/learndash/bp-learndash-integration.php
  src/bp-media/bp-media-cache.php
  src/bp-media/bp-media-filters.php
  src/bp-media/bp-media-functions.php
  src/bp-media/classes/class-bp-media-album.php
  src/bp-media/classes/class-bp-media.php
  src/bp-members/bp-members-cache.php
  src/bp-members/bp-members-functions.php
  src/bp-members/classes/class-bp-members-component.php
  src/bp-members/classes/class-bp-signup.php
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-moderation-component.php
  src/bp-moderation/classes/class-bp-moderation.php
  src/bp-moderation/classes/suspend/class-bp-core-suspend.php
  src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
  src/bp-notifications/bp-notifications-cache.php
  src/bp-notifications/classes/class-bp-notifications-component.php
  src/bp-notifications/classes/class-bp-notifications-notification.php
  src/bp-video/bp-video-cache.php
  src/bp-video/bp-video-filters.php
  src/bp-video/bp-video-functions.php
  src/bp-video/classes/class-bp-video-component.php
  src/bp-xprofile/bp-xprofile-cache.php
  src/bp-xprofile/classes/class-bp-xprofile-component.php
  src/bp-xprofile/classes/class-bp-xprofile-field.php
  src/bp-xprofile/classes/class-bp-xprofile-profiledata.php
Labels: status: changes requested, component: search, component: invites, component: groups, component: notifications, component: moderation, cache, hacktoberfest

#2827 #1746 - Send emails in batches
  src/bp-core/admin/bp-core-admin-schema.php
  src/bp-core/bp-core-actions.php
  src/bp-core/bp-core-dependency.php
  src/bp-core/bp-core-emails.php
  src/bp-core/bp-core-filters.php
  src/bp-core/bp-core-update.php
  src/bp-core/classes/class-bp-email-background-updater.php
  src/bp-core/classes/class-bp-email-queue.php
  src/bp-forums/common/functions.php
  src/bp-groups/bp-groups-functions.php
  src/bp-groups/bp-groups-notifications.php
  src/bp-invites/actions/invites.php
  src/bp-messages/bp-messages-functions.php
  src/bp-moderation/bp-moderation-functions.php
  src/bp-settings/actions/general.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/private-message.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-video/bp-video-functions.php
  src/class-buddypress.php
Labels: feature: enhancement, priority: high, status: ready for release, merged in dev, require: API update, require: platform pro update

#2722 #1772 - fixed: All notifications for Private Group request access are being marked as read once you just visited one of them
  src/bp-groups/bp-groups-notifications.php
Labels: priority: low, component: groups, component: notifications, status: ready for release

#1994 1433 - Fixed the title adding slashed when the post is not submitted
  src/bp-forums/topics/template.php
Labels: bug, priority: medium, status: ready for release

#3086 #3083 - Fixed video popup close button not working in profile section
  src/bp-templates/bp-nouveau/includes/video/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
Labels: bug, priority: critical, status: ready for release, merged in dev

#2845 #1945 - Fix Profile field names not escaped, backslashes added
  src/bp-xprofile/bp-xprofile-filters.php
Labels: status: ready for release

#3103 #2264 - Fix: Importing PHBB forum is not working
  src/bp-forums/admin/actions.php
  src/bp-forums/admin/admin.php
  src/bp-forums/admin/converter.php
  src/bp-forums/admin/converters/phpBB.php
  src/bp-forums/admin/js/converter.js
  src/bp-forums/admin/parser.php
  src/bp-forums/admin/settings.php
  src/bp-forums/admin/styles/admin.css
  src/bp-forums/admin/styles/admin.min.css
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: status: ready for release

#3108 #934 - The avatar in {{{member.card}}} email token is not showing in Outlook
  src/bp-core/classes/class-bp-email-tokens.php
Labels: bug, priority: medium, status: ready for release

#3098 Fix - Profile picture looks blurry even when upload a high resolution picture
  src/bp-core/bp-core-attachments.php
  src/bp-core/js/avatar.js
  src/bp-core/js/avatar.min.js
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_comments.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_comment_form.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_group_header.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_groups_messages.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_layouts.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_messages.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_update_form.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release, require: theme update

#3132 API Enhancement and Fixes for 1.8.1
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-invites/classes/class-bp-rest-invites-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-video/classes/class-bp-rest-video-poster-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
  src/endpoints/assets/android-chrome-192x192.png
  src/endpoints/assets/android-chrome-512x512.png
  src/endpoints/assets/apple-touch-icon.png
  src/endpoints/assets/bootstrap.min.css
  src/endpoints/assets/bootstrap.min.css.map
  src/endpoints/assets/favicon-16x16.png
  src/endpoints/assets/favicon-32x32.png
  src/endpoints/assets/favicon.ico
  src/endpoints/assets/glyphicons-halflings-regular.eot
  src/endpoints/assets/glyphicons-halflings-regular.svg
  src/endpoints/assets/glyphicons-halflings-regular.ttf
  src/endpoints/assets/glyphicons-halflings-regular.woff
  src/endpoints/assets/glyphicons-halflings-regular.woff2
  src/endpoints/assets/main.css
  src/endpoints/assets/prism.css
  src/endpoints/index.html
Labels: status: ready for release, merged in dev

#3079 Update symlink detection logic
  src/bp-core/admin/bp-core-admin-schema.php
  src/bp-core/bp-core-actions.php
  src/bp-core/bp-core-functions.php
  src/bp-core/bp-core-update.php
  src/bp-media/bp-media-settings.php
Labels: bug, priority: high, refactor, status: ready for release, hacktoberfest

#2828 Forum search issue - fixed
  src/bp-forums/forums/functions.php
  src/bp-forums/search/template.php
  src/bp-search/classes/class-bp-search-bbpress-forums.php
Labels: priority: medium, status: ready for release

#1997 Fix # 1843 : Profile Type with WP Roles are not synched when changing Profile Type
  src/bp-invites/bp-invites-functions.php
  src/bp-members/bp-members-functions.php
  src/bp-members/classes/class-bp-members-admin.php
  src/bp-xprofile/screens/edit.php
Labels: bug, priority: medium, status: ready for release

#3161 Avatar API returning wrong Avatar URL
  src/bp-core/bp-core-filters.php
  src/bp-core/bp-core-rest-api.php
Labels: bug, status: ready for release, merged in dev, require: API update

#3176 API Enhancement and Fixes for 1.8.2
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
Labels: bug, status: ready for release, merged in dev
