Repository buddyboss/buddyboss-platform, pull requests merged in 2021-07, with the labels that each got.

#2537 Fix/2220 extra changes
  src/bp-activity/bp-activity-filters.php
  src/bp-forums/activity.php
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, status: needs review

#2551 Older Document Preview Fixes
  src/bp-document/bp-document-functions.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: document, priority: high, status: ready for release

#2557 Fix - video symlink play issue in safari in popup
  src/bp-core/bp-core-functions.php
  src/bp-video/bp-video-filters.php
Labels: Merged in Dev - RFT, bug, component: video, priority: high, status: ready for release

#2574 Fix - Video download when signed url
  src/bp-templates/bp-nouveau/includes/video/functions.php
Labels: Merged in Dev - RFT, bug, component: video, priority: high, status: ready for release

#2575 Fix - Activity image looks blurry
  src/bp-media/bp-media-functions.php
  src/bp-media/classes/class-bp-media.php
  src/bp-moderation/classes/class-bp-moderation-media.php
  src/bp-templates/bp-nouveau/buddypress/media/activity-entry.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: media, priority: high, status: ready for release

#2577 API Fixes Related to the Media and Video symlink
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-performance/classes/class-performance.php
  src/bp-video/classes/class-bp-rest-video-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: Merged in Dev - RFT, bug, status: ready for release

#2556 Adding an option to enable/disable symlinks for helping customers with video/media issues
  src/bp-core/bp-core-actions.php
  src/bp-core/bp-core-functions.php
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-document/bp-document-functions.php
  src/bp-document/classes/class-bp-document.php
  src/bp-media/bp-media-functions.php
  src/bp-media/bp-media-settings.php
  src/bp-moderation/classes/suspend/class-bp-suspend-video.php
  src/bp-templates/bp-nouveau/includes/document/preview.php
  src/bp-templates/bp-nouveau/includes/media/preview.php
  src/bp-templates/bp-nouveau/includes/template-tags.php
  src/bp-templates/bp-nouveau/includes/video/preview.php
  src/bp-video/bp-video-functions.php
Labels: Merged in Dev - RFT, bug, component: video, priority: high, status: ready for release

#1346 Group type is disappearing when an organizer changes any group settings with a profile type
  src/bp-core/admin/bp-core-admin-functions.php
  src/bp-groups/screens/single/admin/group-settings.php
Labels: Merged in Dev - RFT, bug, priority: high, status: ready for release

#1802 When you copy paste from the clipboard, the image do not appear in forum
  src/bp-core/js/vendor/medium-editor.js
  src/bp-core/js/vendor/medium-editor.min.js
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, bug, priority: high, status: ready for release

#2566 Fixed Video player control not show in white background video
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_video.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: Merged in Dev - RFT, QA Passed, bug, component: video, priority: medium, status: ready for release

#2570 Added Videos tab in Group Navigation
  src/bp-groups/classes/class-bp-groups-component.php
  src/bp-templates/bp-nouveau/includes/groups/classes.php
  src/bp-templates/bp-nouveau/includes/groups/functions.php
Labels: Merged in Dev - RFT, bug, component: media, component: video, priority: medium, status: ready for release

#2290 Sync Activity Comments > Update user timeline for Blog, CPTs and Forums auto-generated activity.
  src/bp-activity/bp-activity-filters.php
  src/bp-activity/bp-activity-functions.php
  src/bp-activity/bp-activity-template.php
  src/bp-blogs/bp-blogs-activity.php
  src/bp-blogs/bp-blogs-filters.php
  src/bp-core/admin/bp-core-admin-settings.php
  src/bp-core/admin/css/common-rtl.css
  src/bp-core/admin/css/common-rtl.min.css
  src/bp-core/admin/css/common.css
  src/bp-core/admin/css/common.min.css
  src/bp-core/admin/js/settings-page.js
  src/bp-core/admin/js/settings-page.min.js
  src/bp-core/admin/sass/common.scss
  src/bp-core/admin/settings/bp-admin-setting-activity.php
  src/bp-core/bp-core-options.php
  src/bp-core/bp-core-update.php
  src/bp-forums/activity.php
  src/bp-moderation/bp-moderation-functions.php
  src/bp-templates/bp-nouveau/buddypress/activity/entry.php
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_comments.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_update_form.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/includes/document/loader.php
  src/bp-templates/bp-nouveau/includes/media/loader.php
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/class-buddypress.php
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, QA Passed, feature: enhancement, priority: high, require API changes, require app native update, require theme update, status: ready for release

#2592 Sync Activity Comment > API changes
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: status: ready for release

#2598 Fix - comment button issue
  src/bp-activity/bp-activity-functions.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: activity, priority: critical, status: ready for release

#2607 #2586 - fix php warning for (BB) Latest Activities widget
  src/bp-templates/bp-nouveau/includes/activity/widgets.php
Labels: Merged in Dev - RFT, QA Passed, bug, integration: compatible, status: ready for release

#2609 Group Navigation changes after video tab added
  src/bp-forums/groups.php
  src/bp-groups/classes/class-bp-groups-component.php
  src/bp-integrations/learndash/buddypress/components/BpGroupCourses.php
  src/bp-integrations/learndash/buddypress/components/BpGroupReports.php
  src/bp-templates/bp-nouveau/includes/groups/classes.php
Labels: Merged in Dev - RFT, QA Passed, component: video, feature: enhancement, priority: medium, status: ready for release

#2614 Pasting content with medium editor
  src/bp-core/js/vendor/medium-editor.js
  src/bp-core/js/vendor/medium-editor.min.js
Labels: Merged in Dev - RFT, bug, javascript, priority: high, status: ready for release

#2595 Safari Browser popup video not playing
  src/bp-document/bp-document-functions.php
  src/bp-video/bp-video-filters.php
  src/bp-video/bp-video-functions.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: media, component: video, priority: medium, status: ready for release

#2621 Fix - fatal error
  src/bp-media/bp-media-functions.php
Labels: bug, component: forums

#2623 Improve document performance
  src/bp-document/classes/class-bp-document.php
Labels: Merged in Dev - RFT, performance, status: needs testing

#2237 Moderation > Make Block and Report button less prominent in the frontend
  src/bp-forums/templates/default/bbpress/content-single-forum.php
  src/bp-moderation/bp-moderation-admin.php
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/bp-moderation-functions.php
  src/bp-moderation/classes/class-bp-moderation-activity-comment.php
  src/bp-moderation/classes/class-bp-moderation-activity.php
  src/bp-moderation/classes/class-bp-moderation-comment.php
  src/bp-moderation/classes/class-bp-moderation-document.php
  src/bp-moderation/classes/class-bp-moderation-forum-replies.php
  src/bp-moderation/classes/class-bp-moderation-forum-topics.php
  src/bp-moderation/classes/class-bp-moderation-forums.php
  src/bp-moderation/classes/class-bp-moderation-groups.php
  src/bp-moderation/classes/class-bp-moderation-media.php
  src/bp-moderation/classes/class-bp-moderation-video.php
  src/bp-moderation/screens/block-member-form.php
  src/bp-moderation/screens/content-report-form.php
  src/bp-moderation/screens/reported-content-popup.php
  src/bp-templates/bp-nouveau/buddypress/activity/comment.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/cover-image-header.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/group-header.php
  src/bp-templates/bp-nouveau/buddypress/members/single/cover-image-header.php
  src/bp-templates/bp-nouveau/buddypress/members/single/member-header.php
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_group_header.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_modration_popup.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_user_header.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/includes/groups/template-tags.php
  src/bp-templates/bp-nouveau/includes/members/template-tags.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
  src/bp-templates/bp-nouveau/sass/buddypress.scss
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, feature: enhancement, priority: medium, status: ready for release

#2627 Fix - avatar display issue
  src/bp-core/bp-core-avatars.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#2619 Group Description html encoding
  src/bp-groups/bp-groups-activity.php
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, QA Passed, bug, component: groups, priority: medium, status: ready for release

#2635 Rendered content for activity discussion
  src/bp-activity/classes/class-bp-activity-activity.php
  src/bp-forums/activity.php
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: Merged in Dev - RFT, bug, priority: medium, status: ready for release

#2643 Fix - mov file type issue
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-video/classes/class-bp-video.php
  src/languages/buddyboss.pot
Labels: QA Passed, bug, component: video, priority: high, status: ready for release

#2658 REST - group activity fetch by group id and video thumbnail generation
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-video/classes/class-bp-rest-video-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: Merged in Dev - RFT, bug, status: ready for release

#2286 Fix/1082 - Repeater field issue generate sometime when add fieldset with name Repeater Fieldset
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.js
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.min.js
  src/bp-xprofile/bp-xprofile-filters.php
  src/bp-xprofile/bp-xprofile-repeaters.php
Labels: Merged in Dev - RFT, bug, priority: medium, require API changes, status: ready for release

#2317 Fixed - Date entry in repeatable field is getting changed after drag …
  src/bp-xprofile/bp-xprofile-repeaters.php
  src/bp-xprofile/screens/edit.php
Labels: Merged in Dev - RFT, QA Passed, component: profile fields, status: ready for release

#2583 #2582 - fixed video button display issue on message compose page base…
  src/bp-forums/replies/functions.php
  src/bp-forums/topics/functions.php
  src/bp-messages/bp-messages-functions.php
  src/bp-templates/bp-nouveau/buddypress/media/entry.php
  src/bp-templates/bp-nouveau/buddypress/media/single-album.php
  src/bp-templates/bp-nouveau/buddypress/video/entry.php
  src/bp-templates/bp-nouveau/buddypress/video/index.php
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/includes/video/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: Merged in Dev - RFT, require platform pro update, status: ready for release

#2477 Order for All results tab for members fixed
  src/bp-search/classes/class-bp-search.php
Labels: Merged in Dev - RFT, bug, status: ready for release

#2664 Fix - video popup edit redirect
  src/bp-activity/bp-activity-filters.php
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/video/loader.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: video, status: ready for release

#2668 Activity > blog post activity content excerpt needs to have a wrapper tag
  src/bp-activity/bp-activity-filters.php
Labels: Merged in Dev - RFT, bug, status: ready for release

#2670 Fix - unwanted media create issue
  src/bp-core/bp-core-actions.php
  src/bp-core/bp-core-functions.php
  src/bp-media/bp-media-settings.php
Labels: Merged in Dev - RFT, bug, component: document, component: media, component: video, status: ready for release

#2669 Fixed Uploading a .flv file throws errors in console
  src/bp-core/js/vendor/flv.js
Labels: Merged in Dev - RFT, QA Passed, bug, component: video, priority: medium, status: ready for release

#2677 FIx parse syntax error on latest version
  src/bp-templates/bp-nouveau/includes/groups/template-tags.php
Labels: bug, priority: high, status: ready for release

#2682 Uncaught TypeError: g(...).magnificPopup is not a function - fixed
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
Labels: Merged in Dev - RFT, bug, priority: high, status: ready for release

#2687 Fix php notice in admin components active tab
  src/bp-core/admin/bp-core-admin-components.php
Labels: Merged in Dev - RFT, bug, php, priority: medium, status: ready for release

#2702 API Enhancement and Fixes
  src/bp-activity/classes/class-bp-rest-activity-comment-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-report-endpoint.php
  src/bp-performance/classes/class-performance.php
  src/bp-video/classes/class-bp-rest-video-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-update-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: Merged in Dev - RFT
