Repository buddyboss/buddyboss-platform, pull requests merged in 2021-12, with the labels that each got.

#3144 #3035 - In safari MP4, MOV Video shows the Video format not supported first time after uploaded, when the page is reload its works (mp4) but not mov
  src/bp-core/bp-core-functions.php
Labels: bug, priority: high, status: ready for release, component: video

#3174 #3172 - Fix php syntax error
  src/bp-core/bp-core-attachments.php
Labels: bug, priority: high, status: ready for release

#3155 Fix - Unable to post a forum if page has a pop up from elementor
  src/bp-forums/templates/default/js/editor.js
Labels: priority: medium, status: ready for release, bug: validated

#2911 #2587 - Group Messages
  src/bp-core/bp-core-emails.php
  src/bp-core/classes/class-bp-email-queue.php
  src/bp-groups/bp-groups-functions.php
  src/bp-media/bp-media-filters.php
  src/bp-messages/bp-messages-filters.php
  src/bp-messages/bp-messages-functions.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/public-message.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
Labels: feature: enhancement, priority: high, component: groups, component: messages, refactor, status: ready for release, merged in dev, require: API update, require: app native update, hacktoberfest, hacktoberfest-accepted

#3175 #3152 - fix - undefined function system
  src/bp-groups/classes/class-bp-groups-group.php
Labels: bug, status: ready for release

#3046 #3044 - create album fix
  src/bp-media/bp-media-functions.php
  src/bp-templates/bp-nouveau/buddypress/media/albums.php
  src/bp-templates/bp-nouveau/buddypress/media/entry.php
  src/bp-templates/bp-nouveau/buddypress/media/index.php
  src/bp-templates/bp-nouveau/buddypress/video/albums.php
  src/bp-templates/bp-nouveau/buddypress/video/create-album.php
Labels: bug, component: media, priority: medium, status: ready for release, component: video, hacktoberfest, hacktoberfest-accepted

#3038 Fix deprecated warning for block category filter
  src/bp-core/admin/bp-core-admin-functions.php
Labels: status: ready for release, merged in dev

#3186 Moderation background process gives memory limit error
  src/bp-core/bp-core-actions.php
  src/bp-moderation/classes/class-bp-moderation-activity-comment.php
  src/bp-moderation/classes/class-bp-moderation-comment.php
  src/bp-moderation/classes/class-bp-moderation-component.php
  src/bp-moderation/classes/class-bp-moderation-document.php
  src/bp-moderation/classes/class-bp-moderation-forum-replies.php
  src/bp-moderation/classes/class-bp-moderation-groups.php
  src/bp-moderation/classes/class-bp-moderation-list-table.php
  src/bp-moderation/classes/class-bp-moderation-media.php
  src/bp-moderation/classes/class-bp-moderation-video.php
  src/bp-moderation/classes/class-bp-moderation.php
  src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
  src/bp-moderation/classes/suspend/class-bp-suspend-activity-comment.php
  src/bp-moderation/classes/suspend/class-bp-suspend-activity.php
  src/bp-moderation/classes/suspend/class-bp-suspend-album.php
  src/bp-moderation/classes/suspend/class-bp-suspend-comment.php
  src/bp-moderation/classes/suspend/class-bp-suspend-document.php
  src/bp-moderation/classes/suspend/class-bp-suspend-folder.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum-reply.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum-topic.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum.php
  src/bp-moderation/classes/suspend/class-bp-suspend-group.php
  src/bp-moderation/classes/suspend/class-bp-suspend-media.php
  src/bp-moderation/classes/suspend/class-bp-suspend-member.php
  src/bp-moderation/classes/suspend/class-bp-suspend-message.php
  src/bp-moderation/classes/suspend/class-bp-suspend-video.php
Labels: bug, status: ready for release

#3212 API Enhancement and Fixes for 1.8.3
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
Labels: status: ready for release, require: API update

#3160 #2933 - Fix: Forum page with group associated title tag issue
  src/bp-core/bp-core-functions.php
  src/bp-forums/classes/class-bp-forums-component.php
Labels: priority: medium, status: ready for release, merged in dev

#3071 Performance > Duplicate queries for @mentions when rendering activity feed - Fixed
  src/bp-forums/activity.php
  src/bp-members/bp-members-functions.php
  src/bp-moderation/classes/class-bp-moderation-activity.php
Labels: priority: high, status: ready for release, merged in dev

#3206 #3188 : Group > Private message > All the users are not displayed
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
Labels: priority: high, status: ready for release, merged in dev

#2829 Append topic reply id with the reply url
  src/bp-forums/activity.php
Labels: priority: medium, status: ready for release, merged in dev

#2257 Email invite link for the Hidden Group Go To the 404 Page
  src/bp-core/classes/class-bp-email-tokens.php
Labels: bug, component: groups, priority: medium, status: ready for release

#2639 #1833 - fixed: not showing update nickname on group discussion
  src/bp-groups/classes/class-bp-groups-member-suggestions.php
Labels: bug, component: groups, status: ready for release, merged in dev

#2894 #2751-Fix-Disappearing Comma on Members Page after ajax request
  src/bp-templates/bp-nouveau/includes/ajax.php
Labels: status: ready for release, merged in dev

#2622 Fix - Subgroup detaches from Parent group when updating group "description"
  src/bp-groups/screens/single/admin/edit-details.php
  src/bp-templates/bp-nouveau/includes/groups/template-tags.php
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release, merged in dev

#3211 #3200 : Fixed unknown title text when hit the desktop notification
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
Labels: status: ready for release, merged in dev

#3169 A non-existing image called undefined.png is being requested when using emoji - Fixed
  src/bp-core/js/emojionearea-edited.js
  src/bp-core/js/emojionearea-edited.min.js
Labels: status: ready for release

#3143 #3142 - Fix - query override issue
  src/bp-document/classes/class-bp-document-folder.php
  src/bp-document/classes/class-bp-document.php
  src/bp-media/classes/class-bp-media-album.php
  src/bp-media/classes/class-bp-media.php
  src/bp-video/classes/class-bp-video-album.php
  src/bp-video/classes/class-bp-video.php
Labels: bug, component: media, component: document, status: ready for release, component: video, bug: validated

#3118 Fixed #2946 Removed additional space after mention @name
  src/bp-core/js/mentions.js
  src/bp-core/js/mentions.min.js
Labels: status: ready for release, merged in dev

#3085 Call to undefined function friends_check_friendship_status
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: status: ready for release, merged in dev

#3003 #1227 - Fix: Inconsistent video preview for forum activity feed
  src/bp-core/classes/class-bp-embed.php
Labels: status: ready for release, merged in dev

#2949 Discussion reply notification issue - fixed
  src/bp-forums/notifications.php
Labels: status: ready for release, merged in dev

#3239 API Enhancement and Fixes for 1.8.4
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-types-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-types-endpoint.php
Labels: bug, status: ready for release, merged in dev

#3256 #3255 - Fixed: News feed page meta title showing wrong
  src/bp-forums/classes/class-bp-forums-component.php
Labels: component: forums, status: ready for release
