Repository buddyboss/buddyboss-platform, pull requests merged in 2021-01, with the labels that each got.

#2010 Fixed the query with Group search
  src/bp-search/classes/class-bp-search-groups.php
Labels: bug, priority: medium, status: needs testing

#2019 Private Rest API Wrapper function
  src/bp-core/bp-core-options.php
Labels: status: needs review

#2033 Remove Reporting Categories from navigation menu
  src/bp-moderation/classes/class-bp-moderation-component.php
Labels: bug, priority: medium

#2034 Document Rename Code Refactor
  src/bp-document/bp-document-functions.php
Labels: Merged in Dev - RFT, component: document, refactor, status: needs review

#2016 Fix #2000: PHP 8.0 Deprecate required parameters after optional parameters
  src/bp-core/classes/class-bp-invitation-manager.php
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-groups/classes/class-bp-groups-invitation-manager.php
  src/bp-loader.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
Labels: QA Passed, bug, priority: medium, status: ready for release

#1215 Forums page and Group Discussions are not working with non-english
  src/bp-core/admin/bp-core-admin-components.php
  src/bp-core/admin/bp-core-admin-functions.php
  src/bp-core/admin/bp-core-admin-pages.php
  src/bp-core/bp-core-update.php
  src/bp-forums/groups.php
  src/bp-templates/bp-nouveau/buddypress-functions.php
  src/bp-templates/bp-nouveau/includes/groups/template-tags.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#2052 Fixed - Private message threads does not loads more then 20
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#2027 Initialize REST API Cache
  Gruntfile.js
  src/bp-core/admin/settings/bp-admin-setting-performance.php
  src/bp-core/bp-core-functions.php
  src/bp-core/classes/class-bp-admin.php
  src/bp-performance/bp-performance-admin.php
  src/bp-performance/bp-performance-filters.php
  src/bp-performance/bp-performance-functions.php
  src/bp-performance/bp-performance-loader.php
  src/bp-performance/bp-performance-mu-loader.php
  src/bp-performance/bp-performance-settings.php
  src/bp-performance/classes/class-bp-performance-component.php
  src/bp-performance/classes/class-cache.php
  src/bp-performance/classes/class-helper.php
  src/bp-performance/classes/class-performance.php
  src/bp-performance/classes/class-pre-user-provider.php
  src/bp-performance/classes/class-route-helper.php
  src/bp-performance/classes/class-settings.php
  src/bp-performance/classes/integrations/class-bb-activity.php
  src/bp-performance/classes/integrations/class-bb-documents.php
  src/bp-performance/classes/integrations/class-bb-forums.php
  src/bp-performance/classes/integrations/class-bb-friends.php
  src/bp-performance/classes/integrations/class-bb-groups.php
  src/bp-performance/classes/integrations/class-bb-media-albums.php
  src/bp-performance/classes/integrations/class-bb-media-photos.php
  src/bp-performance/classes/integrations/class-bb-members.php
  src/bp-performance/classes/integrations/class-bb-messages.php
  src/bp-performance/classes/integrations/class-bb-notifications.php
  src/bp-performance/classes/integrations/class-bb-replies.php
  src/bp-performance/classes/integrations/class-bb-topics.php
  src/bp-performance/classes/integrations/class-integration-abstract.php
  src/bp-performance/mu-plugins/buddyboss-api-caching-mu.php
Labels: Merged in Dev - RFT, feature: enhancement, performance, status: ready for release

#2021 Fixed-Photos: Select Album option are still showing even it is disabled
  src/bp-templates/bp-nouveau/buddypress/media/uploader.php
Labels: Merged in Dev - RFT, QA Passed, component: media, status: ready for release

#1978 Fixed the group visibility translation issue
  src/bp-core/classes/class-bp-email-tokens.php
Labels: QA Passed, bug, priority: medium, status: ready for release

#1972 Excluded group type post type from including in query reset in instuc…
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: QA Passed, bug, priority: medium, status: ready for release

#1971 Fix #1898 : Fix showing css in activity when we publish a post
  src/bp-activity/bp-activity-filters.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: critical, status: ready for release

#1904 Fixed the issue with same checkboxes and radio button in member searc…
  src/bp-templates/bp-nouveau/buddypress/common/search/profile-search.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: medium, status: ready for release

#2065 Fix Fatal error
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-performance/classes/integrations/class-bb-documents.php
Labels: bug, component: moderation

#1980 Fix #1899 : Fix User response is missing error showing while sign up
  src/bp-core/js/register.js
  src/bp-core/js/register.min.js
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#2080 Fixed - The LearnDash Integration settings are not saving with multisite
  src/bp-integrations/learndash/core/Settings.php
Labels: learndash, status: needs review

#2070 Fixed - Group name is not syncing between BuddyBoss and LearnDash
  src/bp-integrations/learndash/buddypress/Hooks.php
  src/bp-integrations/learndash/buddypress/Sync.php
  src/bp-integrations/learndash/learndash/Sync.php
  src/bp-integrations/learndash/library/SyncGenerator.php
Labels: Merged in Dev - RFT, QA Passed, learndash, status: ready for release

#1728 Fixed - Cover photo is not showing after uploading while creating a group
  src/bp-core/js/cover-image.js
  src/bp-core/js/cover-image.min.js
Labels: QA Passed, bug, priority: medium, status: ready for release

#2078 Fixed - Problem loading members in Group invite tab while creating group or after group created
  src/bp-templates/bp-nouveau/js/buddypress-group-invites.js
  src/bp-templates/bp-nouveau/js/buddypress-group-invites.min.js
Labels: bug, priority: medium

#2083 Photo more options hover, photo popup shows previous image for a while
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/icons/bb-icons.min.css
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: bug, priority: high, status: needs review
