Repository buddyboss/buddyboss-platform, pull requests merged in 2021-08, with the labels that each got.

#2652 Fixed GamiPress badges UI issue on Forum activity
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release, Merged in Dev - RFT

#2481 Video - Moderation Support and Improvement in reporting functionality
  src/bp-core/bp-core-functions.php
  src/bp-core/bp-core-update.php
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-filters.php
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-moderation-activity-comment.php
  src/bp-moderation/classes/class-bp-moderation-activity.php
  src/bp-moderation/classes/class-bp-moderation-document.php
  src/bp-moderation/classes/class-bp-moderation-media.php
  src/bp-moderation/classes/class-bp-moderation-template.php
  src/bp-moderation/classes/class-bp-moderation-video.php
  src/bp-moderation/classes/suspend/class-bp-core-suspend.php
  src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
  src/bp-moderation/classes/suspend/class-bp-suspend-activity-comment.php
  src/bp-moderation/classes/suspend/class-bp-suspend-activity.php
  src/bp-moderation/classes/suspend/class-bp-suspend-album.php
  src/bp-moderation/classes/suspend/class-bp-suspend-comment.php
  src/bp-moderation/classes/suspend/class-bp-suspend-document.php
  src/bp-moderation/classes/suspend/class-bp-suspend-folder.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum-reply.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum-topic.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum.php
  src/bp-moderation/classes/suspend/class-bp-suspend-group.php
  src/bp-moderation/classes/suspend/class-bp-suspend-media.php
  src/bp-moderation/classes/suspend/class-bp-suspend-member.php
  src/bp-moderation/classes/suspend/class-bp-suspend-video.php
  src/bp-templates/bp-nouveau/includes/template-tags.php
  src/bp-templates/bp-nouveau/includes/video/ajax.php
  src/bp-templates/bp-nouveau/includes/video/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/bp-video/bp-video-filters.php
  src/class-buddypress.php
Labels: feature: enhancement, status: ready for release, Merged in Dev - RFT, require API changes

#2716 Fixed 1082 and 1823 - duplicate fields issues and cannot add another data of repeater fields for a member type
  src/bp-xprofile/bp-xprofile-filters.php
  src/bp-xprofile/bp-xprofile-repeaters.php
Labels: status: ready for release, Merged in Dev - RFT, require API changes

#2532 Fix for #2423 Selecting "Discussions by Last Post" returning /topics/ page 404 error.
  src/bp-forums/common/functions.php
  src/bp-forums/common/template.php
  src/bp-forums/core/functions.php
  src/bp-forums/topics/functions.php
  src/bp-forums/topics/template.php
Labels: bug, status: ready for release, Merged in Dev - RFT

#2695 Fix - m4v file type issue
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-video/classes/class-bp-video.php
Labels: status: ready for release, Merged in Dev - RFT, component: video

#2709 Added Function check for group component is active on Phots and Videos directory page
  src/bp-templates/bp-nouveau/includes/media/functions.php
  src/bp-templates/bp-nouveau/includes/video/functions.php
Labels: bug, status: ready for release, Merged in Dev - RFT

#2739 API Enhancement and Fixes
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-report-endpoint.php
  src/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-repeater-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: status: ready for release, Merged in Dev - RFT

#2693 Random 404 url and table not found issue with moderation
  src/bp-moderation/bp-moderation-filters.php
Labels: bug, status: ready for release, Merged in Dev - RFT, require API changes
