Repository buddyboss/buddyboss-platform, pull requests merged in 2021-03, with the labels that each got.

#1791 Profile photo uploader Dropzone design not look proper on page load
  src/bp-core/css/avatar.css
  src/bp-core/css/avatar.min.css
Labels: QA Passed, bug, priority: medium, status: ready for release

#2060 Fixed - Delete account button is not working from Account > Delete Ac…
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#2085 Fixed - Participant avatar is clickable but participant name is not c…
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-single-list.php
Labels: Merged in Dev - RFT, component: messages, feature: enhancement, priority: medium, status: ready for release

#2204 Removed SQL query and saved via function
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, QA Passed, bug, component: document, status: ready for release

#2113 Group members list in group Send Private Message is not loading when using large resolution
  src/bp-core/css/avatar-rtl.css
  src/bp-core/css/avatar-rtl.min.css
  src/bp-templates/bp-nouveau/common-styles/_bp_groups_messages.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: QA Passed, bug, priority: high, status: ready for release

#2213 Backend "View Tutorial" buttons should be move to top
  src/bp-core/admin/bp-core-admin-pages.php
  src/bp-core/admin/bp-core-admin-settings.php
  src/bp-core/admin/css/common-rtl.css
  src/bp-core/admin/css/common-rtl.min.css
  src/bp-core/admin/css/common.css
  src/bp-core/admin/css/common.min.css
  src/bp-core/admin/sass/common.scss
  src/bp-core/admin/settings/bp-admin-setting-activity.php
  src/bp-core/admin/settings/bp-admin-setting-friends.php
  src/bp-core/admin/settings/bp-admin-setting-general.php
  src/bp-core/admin/settings/bp-admin-setting-groups.php
  src/bp-core/admin/settings/bp-admin-setting-invites.php
  src/bp-core/admin/settings/bp-admin-setting-media.php
  src/bp-core/admin/settings/bp-admin-setting-moderation.php
  src/bp-core/admin/settings/bp-admin-setting-search.php
  src/bp-core/admin/settings/bp-admin-setting-xprofile.php
  src/bp-core/classes/class-bp-admin-tab.php
  src/bp-integrations/learndash/bp-admin-learndash-tab.php
  src/bp-integrations/learndash/bp-learndash-functions.php
  src/bp-integrations/learndash/templates/admin/integration-tab-intro.php
  src/bp-media/bp-media-settings.php
  src/bp-moderation/bp-moderation-settings.php
  src/bp-search/bp-search-settings.php
  src/languages/buddyboss.pot
Labels: feature: enhancement, priority: medium, status: ready for release

#2250 Fixed - select2.min.css issue with rtl
  src/bp-core/bp-core-cssjs.php
  src/bp-core/css/select2-rtl.css
  src/bp-core/css/select2-rtl.min.css
  src/bp-core/css/select2.css
  src/bp-core/css/select2.min-rtl.css
Labels: QA Passed, status: ready for release

#1817 #1811 - Read More option is not working for long comments on Activity…
  src/bp-activity/bp-activity-filters.php
  src/bp-activity/bp-activity-functions.php
Labels: Merged in Dev - RFT, bug, component: activity, php, priority: high, status: ready for release

#2261 Move select2 files to vendor
  src/bp-core/bp-core-cssjs.php
  src/bp-core/css/vendor/select2-rtl.css
  src/bp-core/css/vendor/select2-rtl.min.css
  src/bp-core/css/vendor/select2.css
  src/bp-core/css/vendor/select2.min.css
Labels: bug, css, status: needs review

#2203 Help Section Layout logic update same as "BuddyBoss App > Help"
  src/bp-core/admin/bp-core-admin-help.php
  src/bp-core/admin/js/help.js
  src/bp-core/admin/js/help.min.js
Labels: feature: enhancement, status: needs review

#2200 Fixed the issued with undefined object
  src/bp-activity/bp-activity-cache.php
Labels: bug, priority: medium, status: ready for release

#2031 Fixed-Repeater fields - if you add too many at once it will duplicate the fields in the admin
  src/bp-xprofile/bp-xprofile-repeaters.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: profiles, priority: critical, status: ready for release

#2175 #2100 - Fixed the issue that Hidden Groups Appear in User Profiles
  src/bp-groups/bp-groups-template.php
Labels: Merged in Dev - RFT, bug, component: groups, priority: high, status: ready for release

#2063 Fixed - If someone shares a youtube video to the activity feed and th…
  src/bp-activity/bp-activity-filters.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: medium, status: ready for release

#2042 Fix #1598 : Issues when mentioning a user
  src/bp-core/js/mentions.js
  src/bp-core/js/mentions.min.js
Labels: QA Passed, component: activity, javascript, status: ready for release

#2269 REST Vulnerability https://virusdie.com/verdicts/?id=67233
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: refactor, status: needs review

#2161 Fixed - Incorrect My Groups count when viewed on Group Type page
  src/bp-templates/bp-nouveau/buddypress/common/filters/group-filters.php
  src/bp-templates/bp-nouveau/includes/groups/functions.php
  src/bp-templates/bp-nouveau/includes/template-tags.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: medium, status: ready for release

#2153 Fixed - Elementor maintenance mode is not working
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: QA Passed, bug, priority: low, status: ready for release

#2276 Fix download MU file.
  src/bp-performance/classes/class-performance.php
Labels: bug, status: needs review

#2259 Fix learndsh deprecated function
  src/bp-core/classes/class-bp-admin-tab.php
  src/bp-core/profile-search/bps-xprofile.php
Labels: Merged in Dev - RFT, bug, learndash, status: ready for release

#2090 fix sql query for mysql version 8.0.22
  src/bp-document/bp-document-functions.php
Labels: QA Passed, bug, priority: medium, status: ready for release

#2126 #1544 - Fixed Visibility Settings of Repeater Fields not synced-in on…
  src/bp-templates/bp-nouveau/buddypress/members/single/settings/profile.php
Labels: Merged in Dev - RFT, bug, component: profile fields, priority: medium, status: ready for release

#2275 Added translation fix
  src/bp-forums/admin.php
Labels: bug, priority: medium

#2231 Set actual IDs for component pages
  src/bp-activity/classes/class-bp-activity-theme-compat.php
  src/bp-blogs/classes/class-bp-blogs-theme-compat.php
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-document/classes/class-bp-document-theme-compat.php
  src/bp-groups/classes/class-bp-groups-theme-compat.php
  src/bp-media/classes/class-bp-media-theme-compat.php
  src/bp-members/classes/class-bp-members-theme-compat.php
  src/bp-members/classes/class-bp-registration-theme-compat.php
Labels: bug, priority: medium, status: ready for release
