Repository buddyboss/buddyboss-platform, pull requests merged in 2021-09, with the labels that each got.

#2757 #2690 - quick reply ajax
  src/bp-forums/common/template.php
  src/bp-forums/templates/default/bbpress/form-attachments.php
Labels: status: ready for release, Merged in Dev, require theme update

#2125 Feature/1962 - Message Performance Improvement
  src/bp-core/bp-core-functions.php
  src/bp-messages/bp-messages-filters.php
  src/bp-messages/bp-messages-functions.php
  src/bp-messages/bp-messages-template.php
  src/bp-messages/classes/class-bp-messages-thread.php
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-single-header.php
  src/bp-templates/bp-nouveau/common-styles/_bp_messages.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/languages/buddyboss.pot
Labels: feature: enhancement, priority: high, component: messages, status: ready for release, Merged in Dev, require API changes, require app native update

#2740 Fix Video does not play on specfic server
  src/bp-document/bp-document-functions.php
  src/bp-video/bp-video-filters.php
  src/bp-video/bp-video-functions.php
Labels: bug, priority: high, status: ready for release, Merged in Dev

#2748 Activity Post on Public Group to Private Group do not change the privacy of the post - Fixed
  src/bp-groups/bp-groups-functions.php
Labels: priority: high, Merged in Dev, status: approved

#2703 Elementor conflict parent forum is not getting saved - issue fixed
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: priority: medium, status: ready for release, Merged in Dev

#2689 Fix - SQL errors
  src/bp-core/admin/bp-core-admin-schema.php
  src/bp-forums/admin/converter.php
Labels: bug, priority: medium, status: ready for release, sql

#2713 Privacy policy link the_content filter issue fixed
  src/bp-core/bp-core-catchuri.php
Labels: priority: medium, status: ready for release, Merged in Dev

#2744 Members widget not working when Member Connections component is disabled - Fixed
  src/bp-members/bp-members-widgets.php
  src/bp-members/classes/class-bp-core-members-widget.php
Labels: priority: medium, status: ready for release, Merged in Dev

#2736 Suspended users are getting email notification for group messages - Fixed
  src/bp-groups/classes/class-bp-groups-member.php
  src/bp-messages/bp-messages-functions.php
  src/bp-messages/classes/class-bp-messages-thread.php
  src/bp-moderation/classes/suspend/class-bp-suspend-member.php
Labels: status: needs testing, priority: medium, status: ready for release, Merged in Dev

#2746 Link Preview Image attachment deletion
  src/bp-activity/bp-activity-filters.php
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2720 #2719 - fix - Error in reset password for existing user
  src/bp-integrations/learndash/library/SyncGenerator.php
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2743 Fix - Redundant container when Creating a new Album
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: bug, priority: low, status: ready for release, Merged in Dev

#2373 Escaped the attributes before echo
  src/bp-templates/bp-nouveau/buddypress/search/loop/post-ajax.php
  src/bp-templates/bp-nouveau/buddypress/search/loop/post.php
Labels: bug, priority: low, bug: can't reproduce, status: ready for release, Merged in Dev, bug: needs validating

#2205 Removed hidden profile type users from search result count
  src/bp-core/profile-search/bps-directory.php
  src/bp-search/classes/class-bp-search-members.php
Labels: bug, priority: low, status: ready for release, Merged in Dev

#2673 Fix - PDF document thumbnails not created when Remove Files From Server defined for WP Offload Media
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-core/compatibility/bp-wp-offload-media-helpers.php
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-functions.php
  src/bp-video/bp-video-functions.php
Labels: bug, priority: high, component: media, component: document, status: ready for release, Merged in Dev, component: video, integration: compatible

#2769 fixed Change Password > front end change password function is not wor…
  src/bp-settings/actions/general.php
Labels: bug, priority: critical, component: profiles, status: ready for release, Merged in Dev

#2834 #2833 - Fix orphand media delete attachment issue
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-functions.php
  src/bp-video/bp-video-functions.php
Labels: bug, priority: critical, external issue, status: ready for release

#2795 Fix Video thumbnail is not getting generated when upload video on iPhone device
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
Labels: bug, QA Passed, priority: medium, status: ready for release, Merged in Dev

#2825 API Enhancement and Fixes
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: status: ready for release, Merged in Dev

#2765 Fix - On Photos tab - text & dropdown is overriding
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2810 Code enhancement to check symlink function disabled by server or not.
  src/bp-core/bp-core-actions.php
  src/bp-core/bp-core-functions.php
  src/bp-media/bp-media-settings.php
Labels: refactor, php, status: ready for release

#2787 Members Following Me and Followers widget setting is not working properly
  src/bp-core/classes/class-bp-core-follow-follower-widget.php
  src/bp-core/classes/class-bp-core-follow-following-widget.php
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2893 API Enhancement and Fixes
  package-lock.json
  package.json
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-media/classes/class-bp-rest-media-details-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-video/classes/class-bp-rest-video-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: status: ready for release, Merged in Dev

#2756 Fixed the reporting for Activity content type
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-moderation-abstract.php
  src/bp-moderation/classes/class-bp-moderation-activity-comment.php
  src/bp-moderation/classes/class-bp-moderation-activity.php
  src/bp-moderation/classes/class-bp-moderation-document.php
  src/bp-moderation/classes/class-bp-moderation-forum-replies.php
  src/bp-moderation/classes/class-bp-moderation-forum-topics.php
  src/bp-moderation/classes/class-bp-moderation-media.php
  src/bp-moderation/classes/class-bp-moderation-video.php
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: bug, priority: high, status: ready for release, Merged in Dev, component: moderation, require API changes

#2704 Fixed-Forums total topic count is not consistent
  src/bp-forums/common/functions.php
  src/bp-forums/forums/functions.php
Labels: priority: medium, status: ready for release, Merged in Dev

#2699 Enable copy paste HTML for medium editor
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: priority: medium, status: ready for release, Merged in Dev

#2800 Media Preview Conflict with Elementor Pro Theme Builder
  src/bp-document/bp-document-filters.php
  src/bp-media/bp-media-filters.php
  src/bp-video/bp-video-filters.php
Labels: bug, priority: critical, component: media, elementor, component: document, status: ready for release, Merged in Dev, component: video, integration: compatible, integration: third-party

#2817 Fix topic pagination
  src/bp-forums/topics/template.php
Labels: bug, priority: high, status: ready for release, require app native update

#2786 Duplicate queries on page request
  src/bp-groups/bp-groups-functions.php
  src/bp-members/bp-members-functions.php
Labels: bug, refactor, priority: medium, status: ready for release, Merged in Dev

#2821 .htaccess rules >> The htaccess access rules for bb files protection is no longer working on Apache 2.4
  src/bp-core/bp-core-update.php
  src/bp-document/bp-document-filters.php
  src/bp-media/bp-media-filters.php
  src/bp-video/bp-video-filters.php
  src/class-buddypress.php
Labels: bug, priority: high, status: ready for release, Merged in Dev

#2762 Fixed Notices on Members widgets
  src/bp-members/bp-members-widgets.php
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2443 Fix for showing empty space at the top of link preview and link is not hide when there is additional text
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release

#2759 Wrong Nicknames generating after migrating to buddyboss-platform
  src/bp-xprofile/bp-xprofile-functions.php
Labels: bug, priority: medium, status: ready for release

#2564 Fixed double notifications for posting on blogpost
  src/bp-activity/bp-activity-notifications.php
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2788 Activity post form Gif icon highlighted issue fixed
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2117 Fixed - Forum association with groups
  src/bp-core/bp-core-template.php
  src/bp-core/bp-core-update.php
  src/bp-forums/admin/forums.php
  src/bp-forums/admin/metaboxes.php
  src/bp-forums/admin/settings.php
  src/bp-forums/common/classes.php
  src/bp-forums/common/template.php
  src/bp-forums/forums/functions.php
  src/bp-forums/forums/template.php
  src/bp-forums/groups.php
  src/class-buddypress.php
Labels: bug, priority: high, component: groups, component: forums, status: ready for release, Merged in Dev, require: API update, require: theme update, require: app native update

#2844 #2121 - activity comment sync fixed
  src/bp-activity/bp-activity-filters.php
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-media/bp-media-filters.php
  src/bp-media/bp-media-functions.php
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/includes/document/ajax.php
  src/bp-templates/bp-nouveau/includes/media/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: feature: enhancement, priority: high, component: activity, component: media, component: document, status: ready for release, Merged in Dev, require: API update, require: app native update

#1599 Repair tool offset should start with 0 fix
  src/bp-core/admin/js/settings-page.js
Labels: bug, javascript, status: ready for release

#2884 Fix - Message Block member popup and member listing UI changes
  src/bp-messages/bp-messages-filters.php
  src/bp-messages/classes/class-bp-messages-thread.php
  src/bp-moderation/classes/suspend/class-bp-suspend-member.php
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-single-header.php
  src/bp-templates/bp-nouveau/common-styles/_bp_messages.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: ready for release, Merged in Dev, require: app native update

#2876 Individual forums replies network search issue - fixed
  src/bp-search/classes/class-bp-search-bbpress-forums-replies.php
Labels: status: ready for release, Merged in Dev

#2819 Fix - Video thumbnail should contain the wrapper rather then cover
  src/bp-core/css/vendor/video-js.css
  src/bp-core/css/vendor/video-js.min.css
  src/bp-templates/bp-nouveau/common-styles/_bp_video.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: bug, priority: medium, status: ready for release

#1210 Shortcode [bbp-topic-form] is not working properly when use in Elementor popup template
  src/bp-forums/templates/default/js/common.js
  src/bp-forums/templates/default/js/editor.js
Labels: bug, component: forums, status: ready for release, require: theme update

#1683 1566 - Fixed the issue with content, subject and link when Wishlist Member plugin is activated
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: bug, priority: medium, status: ready for release, Merged in Dev

#2898 #2897 - Fix - Inconsistent functions uses
  src/bp-activity/bp-activity-admin.php
  src/bp-activity/classes/class-bp-activity-list-table.php
  src/bp-activity/classes/class-bp-activity-oembed-extension.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-blogs/classes/class-bp-rest-blogs-endpoint.php
  src/bp-core/admin/bp-core-admin-components.php
  src/bp-core/admin/bp-core-admin-tools.php
  src/bp-core/bp-core-tools-default-data.php
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-forums/common/functions.php
  src/bp-groups/bp-groups-admin.php
  src/bp-groups/classes/class-bp-groups-list-table.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-media/bp-media-filters.php
  src/bp-members/classes/class-bp-members-admin.php
  src/bp-members/classes/class-bp-rest-members-actions-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-messages/bp-messages-filters.php
  src/bp-messages/bp-messages-template.php
  src/bp-messages/classes/class-bp-messages-thread.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-moderation-list-table.php
  src/bp-moderation/screens/single/admin/report-single.php
  src/bp-notifications/bp-notifications-adminbar.php
  src/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  src/bp-templates/bp-nouveau/buddypress/media/album-entry.php
  src/bp-templates/bp-nouveau/buddypress/media/single-album.php
  src/bp-templates/bp-nouveau/buddypress/search/loop/albums-ajax.php
  src/bp-templates/bp-nouveau/buddypress/search/loop/albums.php
  src/bp-templates/bp-nouveau/buddypress/video/album-entry.php
  src/bp-templates/bp-nouveau/buddypress/video/single-album.php
  src/bp-templates/bp-nouveau/includes/document/functions.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/includes/media/functions.php
  src/bp-templates/bp-nouveau/includes/template-tags.php
  src/bp-templates/bp-nouveau/includes/video/functions.php
  src/bp-video/bp-video-filters.php
  src/bp-xprofile/bp-xprofile-filters.php
Labels: php, priority: medium, status: ready for release, Merged in Dev, require: API update

#2901 Fix Header Search Bar - Multiple issues and Improvements
  src/bp-templates/bp-nouveau/js/buddypress-search.js
  src/bp-templates/bp-nouveau/js/buddypress-search.min.js
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: ready for release, Merged in Dev, require: theme update

#2599 Fixed: "and" string unable translate in the login page
  src/bp-core/bp-core-catchuri.php
  src/languages/buddyboss.pot
Labels: status: ready for release

#2928 Fixed media upload error message
  src/bp-media/bp-media-functions.php
Labels: status: ready for release

#2549 #2548 - PHP8 compatibility issue fixed
  src/bp-search/classes/class-bp-search-types.php
Labels: status: ready for release

#2770 #2768 - fix - Removed the commented line form the flv.js file
  src/bp-core/js/vendor/flv.js
Labels: bug, status: ready for release

#2801 Fix discussion reply with document not loading when documents upload disabled for activity
  src/bp-forums/templates/default/bbpress/form-attachments.php
Labels: status: ready for release

#2822 fix: Profile Search with Search all fields has Undefined id
  src/bp-core/profile-search/bps-search.php
  src/bp-xprofile/bp-xprofile-repeaters.php
Labels: refactor, status: ready for release

#2826 fix: Unread message count shows wrong at the top bar. #2097
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: status: ready for release

#2837 #2447- Fix - Connection tab on the activity feed is also showing the logged in member own activity
  src/bp-friends/bp-friends-activity.php
Labels: status: ready for release

#2842 #2239 - Fix getting an error on jquery.atwho.min.js in console
  src/bp-core/js/vendor/jquery.atwho.js
Labels: status: ready for release

#2861 #2514 - In Forum Discussion Reply, user post second GIF, it gives dup…
  src/bp-forums/common/functions.php
Labels: status: ready for release

#2925 #1951-fix-documentation change for nickname 3 characters
  src/bp-xprofile/bp-xprofile-filters.php
Labels: QA Passed, status: ready for release

#2508 2398 # Single quote in user name or last name is not appearing correctly in private message.
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-single-list.php
Labels: bug, component: messages, status: ready for release, Merged in Dev

#2838 Fix - Line break is not working in the Paragraph Text Field
  src/bp-templates/bp-nouveau/common-styles/_bp_tables.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: ready for release

#2938 Fix - Document, Video & Photo Download security issue
  src/bp-document/bp-document-filters.php
  src/bp-media/bp-media-functions.php
  src/bp-video/bp-video-functions.php
Labels: priority: high, component: media, component: document, status: ready for release, component: video

#2991 Cross-Site Scripting (XSS) issue with search feature
  src/bp-search/bp-search-functions.php
Labels: priority: critical, status: ready for release, Merged in Dev

#2905 #2858 - fixed topics same slug tag does not add issue
  src/bp-forums/functions.php
  src/bp-forums/replies/functions.php
  src/bp-forums/templates/default/js/common.js
  src/bp-forums/topics/functions.php
Labels: status: ready for release, Merged in Dev, require: API update, require: app native update

#2008 #2006 add filter to skip strip out script
  src/bp-core/bp-core-catchuri.php
Labels: bug, priority: medium, status: ready for release
