Repository buddyboss/buddyboss-platform, pull requests merged in 2021-05, with the labels that each got.

#2362 Redirect to discussion page after create new discussion
  src/bp-core/bp-core-catchuri.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#1835 #1834 Fixed Member/Profile types draft status
  src/bp-groups/bp-groups-functions.php
  src/bp-members/bp-members-functions.php
Labels: Merged in Dev - RFT, bug, component: groups, status: ready for release

#2137 Fixed - Duplicate New Reply Notification
  src/bp-forums/notifications.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: medium, status: ready for release

#2392 Profile > Courses returns 404 when Learndash Courses URL is nested
  src/bp-core/bp-core-catchuri.php
  src/bp-integrations/learndash/bp-learndash-filters.php
  src/bp-integrations/learndash/bp-learndash-functions.php
  src/bp-integrations/learndash/core/Core.php
Labels: Merged in Dev - RFT, bug, learndash, priority: medium, status: ready for release

#2328 Optimize group member count query
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/public-message.php
  src/bp-templates/bp-nouveau/includes/template-tags.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: high, status: ready for release

#2246 fix bp_member_get_report_link function get_users slow query
  src/bp-members/bp-members-functions.php
Labels: Merged in Dev - RFT, bug, feature: enhancement, performance, status: ready for release

#2147 Fixed - Infinite loading after deleting messages
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: Merged in Dev - RFT, bug, priority: medium, status: ready for release

#2321 Fixed injecting script/image in the document through URL
  src/bp-templates/bp-nouveau/buddypress/search/results-page.php
  src/bp-templates/bp-nouveau/buddypress/search/search-form.php
Labels: Merged in Dev - RFT, bug, status: ready for release

#1659 Fixed While uploading Profile photo or cover photo, it should update instantly on page
  src/bp-core/js/avatar.js
  src/bp-core/js/avatar.min.js
  src/bp-core/js/cover-image.js
  src/bp-core/js/cover-image.min.js
Labels: QA Passed, bug, feature: enhancement, priority: medium, status: ready for release

#2291 Fixed iPhone-11 send message issue
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, priority: medium, status: ready for release

#2394 fixed - Notification after mark as Unread not showing properly in Unr…
  src/bp-notifications/classes/class-bp-notifications-notification.php
Labels: Merged in Dev - RFT, component: notifications, status: ready for release

#2012 Firefox comment/reply anchoring
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, accessibility, bug, component: activity, priority: medium, status: ready for release

#1771 Forums notification settings in Member’s Email Preferences to stop receiving email
  src/bp-core/gdpr/class-bp-settings-export.php
  src/bp-forums/common/functions.php
  src/bp-forums/groups.php
  src/bp-friends/bp-friends-notifications.php
Labels: API changes needed, Merged in Dev - RFT, QA Passed, component: forums, feature: enhancement, priority: medium, status: ready for release

#2271 Fix Redis Cache issues
  src/bp-media/classes/class-bp-media-component.php
  src/bp-templates/bp-nouveau/includes/document/ajax.php
  src/bp-templates/bp-nouveau/includes/media/ajax.php
Labels: Merged in Dev - RFT, bug, cache, component: document, component: media, php, status: ready for release

#2408 API and Performance fixes
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/bp-core-rest-api.php
  src/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  src/bp-performance/classes/integrations/class-bb-groups.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: status: needs review

#2411 Group type 404 when invalid group type into URL
  src/bp-groups/classes/class-bp-groups-component.php
Labels: Merged in Dev - RFT, bug, status: ready for release

#2412 Creating a discussion within a hidden group redirects to the homepage
  src/bp-core/bp-core-catchuri.php
Labels: Merged in Dev - RFT, QA Passed, refactor, status: ready for release

#1727 #1360 - Fix Document/Media/Video capability based on Group settings
  src/bp-core/deprecated/buddyboss/1.7.0.php
  src/bp-document/bp-document-filters.php
  src/bp-document/bp-document-functions.php
  src/bp-document/bp-document-template.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-groups/bp-groups-admin.php
  src/bp-groups/classes/class-bp-rest-group-settings-endpoint.php
  src/bp-media/bp-media-functions.php
  src/bp-media/bp-media-template.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-templates/bp-nouveau/buddypress/document/activity-document-actions.php
  src/bp-templates/bp-nouveau/buddypress/document/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/audio-preview.php
  src/bp-templates/bp-nouveau/buddypress/document/code-preview.php
  src/bp-templates/bp-nouveau/buddypress/document/doc-preview.php
  src/bp-templates/bp-nouveau/buddypress/document/document-entry.php
  src/bp-templates/bp-nouveau/buddypress/document/single-folder.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/admin/group-settings.php
  src/bp-templates/bp-nouveau/buddypress/media/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/media/entry.php
  src/bp-templates/bp-nouveau/buddypress/media/single-album.php
  src/bp-templates/bp-nouveau/buddypress/video/activity-entry.php
  src/bp-templates/bp-nouveau/buddypress/video/entry.php
  src/bp-templates/bp-nouveau/buddypress/video/single-album.php
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/includes/document/ajax.php
  src/bp-templates/bp-nouveau/includes/document/player.php
  src/bp-templates/bp-nouveau/includes/document/preview.php
  src/bp-templates/bp-nouveau/includes/media/ajax.php
  src/bp-templates/bp-nouveau/includes/video/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-video/bp-video-filters.php
  src/bp-video/bp-video-functions.php
  src/languages/buddyboss.pot
Labels: API changes needed, component: document, component: groups, component: media, feature: enhancement, priority: medium, status: in progress

#2432 Update - "Search GIFs" to "Search GIPHY"
  src/bp-forums/templates/default/bbpress/form-attachments.php
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-gif-media-search-dropdown.php
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-gif-media-search-dropdown.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/private-message.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/public-message.php
Labels: Merged in Dev - RFT, QA Passed, feature: enhancement, priority: medium, status: ready for release

#2382 Member search for learndash open course
  src/bp-core/profile-search/bps-search.php
  src/bp-integrations/learndash/learndash/Hooks.php
Labels: API changes needed, Merged in Dev - RFT, bug, status: ready for release

#1486 Fix activation key error message (fixes #1485)
  src/bp-members/bp-members-functions.php
  src/bp-members/classes/class-bp-signup.php
Labels: Merged in Dev - RFT, bug, php, priority: medium, status: ready for release

#2347 Timeline preview image is not working
  src/bp-templates/bp-nouveau/includes/document/preview.php
Labels: Merged in Dev - RFT, QA Passed, bug, priority: medium, status: ready for release

#2233 Fixed the user nickmane already exist issue
  src/bp-core/admin/bp-core-admin-actions.php
Labels: Merged in Dev - RFT, bug, priority: medium, status: ready for release

#2406 Fix for Notifications for commenting on Blog post not working on Plat…
  src/bp-activity/bp-activity-functions.php
  src/bp-blogs/bp-blogs-functions.php
Labels: Merged in Dev - RFT, bug, status: ready for release
