Repository buddyboss/buddyboss-platform, pull requests merged in 2021-02, with the labels that each got.

#1999 Fixed-Disappearing comments after editing posts and custom post types
  src/bp-activity/bp-activity-functions.php
  src/bp-blogs/bp-blogs-functions.php
  src/bp-moderation/classes/suspend/class-bp-suspend-comment.php
Labels: QA Passed, bug, component: activity, status: ready for release

#2089 Fixed - On Create Group page cover image placeholder should only show when image is uploaded
  src/bp-core/js/cover-image.js
  src/bp-core/js/cover-image.min.js
  src/bp-templates/bp-nouveau/buddypress/groups/single/admin/group-cover-image.php
  src/bp-templates/bp-nouveau/common-styles/_bp_item_header_general.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, priority: medium, status: needs review

#2105 API Feature - Member Access Controls
  src/bp-activity/classes/class-bp-rest-activity-comment-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-document/classes/class-bp-rest-document-folder-endpoint.php
  src/bp-forums/classes/class-bp-rest-forums-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
  src/bp-groups/classes/class-bp-rest-attachments-group-cover-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-settings-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-types-endpoint.php
  src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-members-component.php
  src/bp-members/classes/class-bp-rest-attachments-member-avatar-endpoint.php
  src/bp-members/classes/class-bp-rest-attachments-member-cover-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-members/classes/class-bp-rest-members-permissions-endpoint.php
  src/bp-members/classes/class-bp-rest-signup-endpoint.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-report-endpoint.php
  src/bp-performance/classes/integrations/class-bb-notifications.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-types-endpoint.php
  src/class-buddypress.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: enhancement, priority: medium, status: needs review

#2108 Fixed misaligned "Select Folder/Album" button in Photo and document uploader popup
  src/bp-templates/bp-nouveau/buddypress/document/document-uploader.php
  src/bp-templates/bp-nouveau/buddypress/media/uploader.php
  src/languages/buddyboss.pot
Labels: bug, priority: high, status: needs review

#2106 Fix - Activity & Message issue
  src/bp-templates/bp-nouveau/buddypress/activity/index.php
  src/bp-templates/bp-nouveau/includes/activity/ajax.php
  src/bp-templates/bp-nouveau/includes/activity/functions.php
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/languages/buddyboss.pot
Labels: bug, component: membership, status: needs review

#2136 Rest Refector Access Control
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  src/bp-members/classes/class-bp-rest-members-permissions-endpoint.php
  src/bp-performance/classes/integrations/class-bb-media-albums.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: refactor

#2144 Refactor: API Caching
  src/bp-performance/classes/class-helper.php
  src/bp-performance/classes/class-performance.php
  src/bp-performance/classes/class-pre-user-provider.php
  src/bp-performance/classes/class-route-helper.php
  src/bp-performance/classes/class-settings.php
  src/bp-performance/classes/integrations/class-bb-activity.php
  src/bp-performance/classes/integrations/class-bb-documents.php
  src/bp-performance/classes/integrations/class-bb-forums.php
  src/bp-performance/classes/integrations/class-bb-friends.php
  src/bp-performance/classes/integrations/class-bb-groups.php
  src/bp-performance/classes/integrations/class-bb-media-albums.php
  src/bp-performance/classes/integrations/class-bb-media-photos.php
  src/bp-performance/classes/integrations/class-bb-members.php
  src/bp-performance/classes/integrations/class-bb-messages.php
  src/bp-performance/classes/integrations/class-bb-notifications.php
  src/bp-performance/classes/integrations/class-bb-replies.php
  src/bp-performance/classes/integrations/class-bb-topics.php
  src/bp-performance/classes/integrations/class-integration-abstract.php
Labels: refactor, status: needs review

#2145 Fix fatal error on send message
  src/bp-messages/bp-messages-functions.php
Labels: Merged in Dev - RFT, bug, component: messages, php, priority: critical, status: ready for release

#2156 Fix - missing quotes
  src/bp-groups/bp-groups-template.php
Labels: bug

#2143 Added select all in private message in group message
  src/bp-groups/bp-groups-filters.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/private-message.php
  src/bp-templates/bp-nouveau/buddypress/groups/single/messages/public-message.php
  src/bp-templates/bp-nouveau/common-styles/_bp_groups_messages.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/includes/groups/functions.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/languages/buddyboss.pot
Labels: bug, component: groups, component: messages, status: needs review, status: needs testing

#1979 Fix #1851 : Fix error 404 when a user leaves a hidden group
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
Labels: bug, priority: medium, status: ready for release
