Repository buddyboss/buddyboss-platform, pull requests merged in 2021-06, with the labels that each got.

#2439 Group Message send multiple times when triggering the 'send message' button multiple time
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
Labels: Merged in Dev - RFT, QA Passed, bug, priority: medium, status: ready for release

#2449 Activity -> editing an activity post change button to Update Post
  src/bp-templates/bp-nouveau/includes/activity/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, QA Passed, bug, component: activity, priority: medium, status: ready for release

#2416 Platform Help section consistent with App Plugin help section
  src/bp-core/admin/js/help.js
  src/bp-core/admin/js/help.min.js
Labels: Merged in Dev - RFT, QA Passed, feature: enhancement, priority: medium, status: ready for release

#2387 Fixed the issue Sharing Document link in Private message
  src/bp-core/bp-core-functions.php
  src/bp-core/classes/class-bp-embed.php
  src/bp-forums/replies/functions.php
  src/bp-forums/topics/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/languages/buddyboss.pot
Labels: Merged in Dev - RFT, bug, component: messages, priority: high, status: ready for release

#1832 Fixed - Default content &#8203; when adding gif and refactor gif module correctly
  src/bp-activity/bp-activity-filters.php
  src/bp-activity/bp-activity-functions.php
  src/bp-media/bp-media-filters.php
  src/bp-templates/bp-nouveau/includes/activity/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/languages/buddyboss.pot
Labels: API changes needed, Merged in Dev - RFT, feature: enhancement, status: ready for release

#2457 API Fixes
  src/bp-activity/classes/class-bp-rest-activity-comment-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-repeater-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-update-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: bug, status: needs review

#2451 Added new icons for TikTok, Telegram and ClubHouse
  src/bp-templates/bp-nouveau/icons/bb-icons.css
  src/bp-templates/bp-nouveau/icons/bb-icons.eot
  src/bp-templates/bp-nouveau/icons/bb-icons.svg
  src/bp-templates/bp-nouveau/icons/bb-icons.ttf
  src/bp-templates/bp-nouveau/icons/bb-icons.woff
  src/bp-templates/bp-nouveau/icons/bb-icons.woff2
  src/bp-templates/bp-nouveau/icons/config.json
Labels: feature: enhancement, priority: high, require theme update, status: ready for release

#2433 Added caching functions to prevent the repeated SQL queries
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-moderation.php
  src/bp-moderation/classes/suspend/class-bp-core-suspend.php
  src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
  src/bp-moderation/classes/suspend/class-bp-suspend-comment.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum-reply.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum-topic.php
  src/bp-moderation/classes/suspend/class-bp-suspend-forum.php
  src/bp-moderation/classes/suspend/class-bp-suspend-message.php
Labels: Merged in Dev - RFT, bug, priority: high, status: ready for release

#1977 Fix # 1810 : Irrelevant names are showing when searching a user in the private messaging
  src/bp-core/bp-core-functions.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: Merged in Dev - RFT, QA Passed, bug, component: messages, status: needs testing, status: ready for release

#2446 The subscriber does not appear as a group leader from the Learndash dashboard, after creating group from the BB front-end.
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-integrations/learndash/library/SyncGenerator.php
Labels: Merged in Dev - RFT, bug, learndash, priority: medium, status: ready for release

#2496 Custom Profile and Group tab support in Platform and Theme
  src/bp-templates/bp-nouveau/common-styles/_bp_user_profile.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: Merged in Dev - RFT, QA Passed, feature: enhancement, priority: medium, status: ready for release

#2515 Pulled Platform API release latest changes
  src/bp-forums/classes/class-bp-rest-reply-actions-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: component: forums, feature: enhancement

#1788 #662 - Topic Reply Pagination
  src/bp-forums/common/ajax.php
  src/bp-forums/common/functions.php
  src/bp-forums/common/template.php
  src/bp-forums/core/actions.php
  src/bp-forums/replies/functions.php
  src/bp-forums/replies/template.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: forums, priority: high, require API changes, require theme update, status: ready for release

#2379 Fix #2306 : Fix discussions were not getting in search result
  src/bp-search/classes/class-bp-search-bbpress-forums-topics.php
Labels: bug, priority: medium, status: ready for release

#2479 Trashed reply restore fix
  src/bp-forums/core/actions.php
  src/bp-forums/replies/functions.php
Labels: Merged in Dev - RFT, bug, status: ready for release

#1826 Fixed Html posted in content is lost on editing the discussion
  src/bp-forums/templates/default/js/common.js
Labels: QA Passed, bug, component: forums, priority: medium, status: ready for release

#1844 Fixed the validation for html characters
  src/bp-xprofile/classes/class-bp-xprofile-field-type.php
Labels: QA Passed, bug, priority: medium, status: ready for release

#1567 Fixed - RTL Site crop tool for Group profile photo works abnormally
  src/bp-core/css/avatar-rtl.css
  src/bp-core/css/avatar-rtl.min.css
  src/bp-core/css/avatar.css
  src/bp-core/css/avatar.min.css
  src/languages/buddyboss.pot
Labels: QA Passed, bug, priority: medium, status: ready for release

#1528 Avatar show blank when in WP Settings Discussion > Avatar Display > OFF
  src/bp-core/bp-core-avatars.php
  src/bp-core/deprecated/buddyboss/1.6.4.php
  src/class-buddypress.php
Labels: Merged in Dev - RFT, QA Passed, bug, component: profiles, status: ready for release

#2517 Added filter for blog post feature media
  src/bp-activity/bp-activity-filters.php
Labels: Merged in Dev - RFT, feature: enhancement, php, refactor, status: ready for release

#1169 Fixed Numbered list formatting issue
  src/bp-core/js/vendor/medium-editor.js
  src/bp-core/js/vendor/medium-editor.min.js
  src/languages/buddyboss.pot
Labels: QA Passed, bug, design, priority: medium, require theme update, status: ready for release

#2524 API Fixes
  src/bp-activity/classes/class-bp-rest-activity-comment-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-details-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-link-preview-endpoint.php
  src/bp-core/classes/class-bp-rest-components-endpoint.php
  src/bp-core/classes/class-bp-rest-mention-endpoint.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-document/classes/class-bp-rest-document-folder-endpoint.php
  src/bp-forums/classes/class-bp-rest-forums-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-actions-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-actions-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-friends/classes/class-bp-rest-friends-endpoint.php
  src/bp-groups/classes/class-bp-rest-attachments-group-avatar-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-invites-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-membership-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-membership-request-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-settings-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-details-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-integrations/learndash/classes/class-bp-rest-learndash-courses-endpoint.php
  src/bp-invites/classes/class-bp-rest-invites-endpoint.php
  src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-rest-members-actions-endpoint.php
  src/bp-members/classes/class-bp-rest-members-details-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-members/classes/class-bp-rest-members-permissions-endpoint.php
  src/bp-members/classes/class-bp-rest-signup-endpoint.php
  src/bp-messages/classes/class-bp-rest-group-messages-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-actions-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-report-endpoint.php
  src/bp-notifications/classes/class-bp-rest-notifications-endpoint.php
  src/bp-settings/classes/class-bp-rest-account-settings-endpoint.php
  src/bp-settings/classes/class-bp-rest-account-settings-options-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-data-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-fields-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-repeater-endpoint.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-update-endpoint.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: Merged in Dev - RFT, feature: enhancement, refactor, status: ready for release

#2519 On-Screen notification > WP admin settings
  src/bp-core/admin/bp-core-admin-settings.php
  src/bp-core/admin/css/common-rtl.css
  src/bp-core/admin/css/common-rtl.min.css
  src/bp-core/admin/css/common.css
  src/bp-core/admin/css/common.min.css
  src/bp-core/admin/sass/common.scss
  src/bp-core/admin/settings/bp-admin-setting-notifications.php
  src/bp-core/classes/class-bp-admin.php
  src/bp-core/images/admin/icons/fontawesome/regular/bells.svg
  src/bp-notifications/bp-notifications-functions.php
  src/bp-notifications/bp-notifications-template.php
  src/bp-templates/bp-nouveau/buddypress/notifications/on-screen.php
  src/bp-templates/bp-nouveau/common-styles/_bp_on_screen_notification.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/notifications/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/bp-templates/bp-nouveau/sass/buddypress.scss
  src/languages/buddyboss.pot
Labels: require theme update, status: needs testing

#2542 Rest API and Cache support for Video
  Gruntfile.js
  src/bp-activity/classes/class-bp-rest-activity-comment-endpoint.php
  src/bp-activity/classes/class-bp-rest-activity-endpoint.php
  src/bp-core/classes/class-bp-rest-settings-endpoint.php
  src/bp-core/classes/trait-bp-rest-attachments.php
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-forums/classes/class-bp-rest-reply-endpoint.php
  src/bp-forums/classes/class-bp-rest-topics-endpoint.php
  src/bp-groups/classes/class-bp-rest-group-settings-endpoint.php
  src/bp-groups/classes/class-bp-rest-groups-endpoint.php
  src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-rest-members-endpoint.php
  src/bp-members/classes/class-bp-rest-members-permissions-endpoint.php
  src/bp-messages/classes/class-bp-rest-messages-endpoint.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
  src/bp-performance/classes/class-option-clear-cache.php
  src/bp-performance/classes/class-performance.php
  src/bp-performance/classes/class-settings.php
  src/bp-performance/classes/integrations/class-bb-media-albums.php
  src/bp-performance/classes/integrations/class-bb-videos.php
  src/bp-video/classes/class-bp-rest-video-details-endpoint.php
  src/bp-video/classes/class-bp-rest-video-endpoint.php
  src/bp-video/classes/class-bp-rest-video-poster-endpoint.php
  src/bp-video/classes/class-bp-video-component.php
  src/bp-xprofile/classes/class-bp-rest-xprofile-field-groups-endpoint.php
  src/class-buddypress.php
  src/endpoints/api_data.js
  src/endpoints/api_data.json
  src/endpoints/api_project.js
  src/endpoints/api_project.json
Labels: feature: enhancement, status: needs review
