Repository buddyboss/buddyboss-platform, pull requests merged in 2022-07, with the labels that each got.

#3197 PROD-683 #3179 - Fix: the [bbp-search] shortcode is not showing the search input
  src/bp-forums/search/template.php
Labels: status-needs-review

#2663 PROD-780 Fix - Theater view improvement for iPad Pro
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_video.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: bug, status-needs-qa, priority-medium

#2791 PROD-896 Thumbnail preview is not generated issue - fixed
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: status-needs-qa, t3-ready-for-qa

#3345 Basic HTML Codes not working on group description - Fixed
  src/bp-groups/bp-groups-filters.php
Labels: status-needs-qa, t3-needs-review

#3262 PROD-652 - Create album button issue for group - Fixed
  src/bp-templates/bp-nouveau/buddypress/media/albums.php
Labels: needs-final-review, t3-needs-review

#3371 Groups & Profile Tab links are not working properly with WPML plugin
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-core/compatibility/class-bb-wpml-helpers.php
Labels: status-needs-qa, t3-needs-review

#3423 [PROD-2519] Learndash group slug changing issue fixed
  src/bp-integrations/learndash/bp-learndash-filters.php
Labels: status-needs-qa

#2389 PROD-827 PROD-931 Profile search is not working properly for Repeater field set dropdown - Fixed.
  src/bp-core/profile-search/bps-xprofile.php
Labels: bug, needs-final-review, t3-needs-review

#2485 PROD-805 Recently Active Members widget "More >" button issue fixed
  src/bp-members/classes/class-bp-core-recently-active-widget.php
Labels: needs-final-review, t3-needs-review
