Repository buddyboss/buddyboss-platform, pull requests merged in 2022-03, with the labels that each got.

#3013 PROD-733 Fix - Bullet list formatted reply from discussion is not showing properly on activity feed
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: bug, status-needs-qa, priority-medium

#3238 PROD-662 Fixed #3237 minified jquery.atwho.min.js file
  src/bp-core/js/vendor/jquery.atwho.min.js
Labels: status-needs-qa, merged-in-dev, t3-ready-for-qa

#3258 PROD-653 #fixed 3257 changes made for directory slug as group key
  src/bp-groups/bp-groups-functions.php
Labels: status-needs-qa, merged-in-dev, t3-ready-for-qa

#3388 [PROD-2363] New line not working for Setting > Privacy > Public Website Content field - Fixed
  src/bp-core/classes/class-bp-admin-tab.php
Labels: status-needs-review, t3-needs-review

#3351 Activity post form privacy settings not working issue fixed
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: status-needs-review, t3-needs-review

#3334 PROD-2136 - Fixed fatal error when update user details
  src/bp-xprofile/bp-xprofile-filters.php
Labels: bug, t3-needs-review

#3332 Fatal error: Memory exhausted when trying to view group as non logged in user and when there is a large number of group invitations
  src/bp-groups/bp-groups-functions.php
Labels: status-needs-review, t3-needs-review
