Repository buddyboss/buddyboss-platform, pull requests merged in 2022-10, with the labels that each got.

#3303 PROD-1980 - fixed error when blocking user and activity component is disabled
  src/bp-moderation/bp-moderation-filters.php
  src/bp-moderation/classes/class-bp-rest-moderation-endpoint.php
Labels: status-needs-qa

#3570 PROD-3225 Fixed parent group icon tooltip position
  src/bp-groups/bp-groups-template.php
Labels: status-needs-review, t3-needs-review

#2968 PROD-835 Fix 2325 Add the condition to the destroy uploader for the respective uploader type on change
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: needs-final-review, t3-needs-review

#2636 PROD-822 The Conversation doesn't fetch if the username registered with dot (.) inside the username
  src/bp-templates/bp-nouveau/includes/members/template-tags.php
Labels: bug, status-needs-review

#3228 PROD-678 View page of the Elementor saved template not working - Fixed
  src/bp-core/compatibility/bp-elementor-plugin-helpers.php
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: status-needs-review, integration-official, t3-inprogress

#2924 PROD-938 #1136 - Fix PHP Error: Add fix for About Forum link of dashboard
  src/bp-forums/admin/admin.php
Labels: needs-final-review, t3-needs-review

#3201 PROD-708#3095 fix filtered moderated users from the bp_get_followers and bp_get_following functions
  src/bp-activity/classes/class-bp-activity-follow.php
  src/bp-moderation/classes/suspend/class-bp-suspend-member.php
Labels: t3-ready-for-qa

#3178 PROD-687 #3166 - Fix video page woo membership restriction
  src/bp-video/classes/class-bp-video-theme-compat.php
Labels: bug, status-needs-review, feature-video, integration-compatible
