Repository buddyboss/buddyboss-platform, pull requests merged in 2022-11, with the labels that each got.

#3268 PROD-649 "is one of" search mode issue for gender field in profile search - Fixed
  src/bp-core/profile-search/bps-xprofile.php
Labels: status-needs-qa, t3-inprogress

#3154 PROD-909 Disable the registration page mapping on activity settings save
  src/bp-core/admin/settings/bp-admin-setting-activity.php
  src/bp-core/bp-core-functions.php
Labels: bug, t3-ready-for-qa

#2796 PROD-890 #1822 - Fix: The profile completion widget is not updating after profile type was changed
  src/bp-core/bp-core-functions.php
  src/bp-xprofile/bp-xprofile-filters.php
Labels: feature-member-profiles, status-needs-qa, t3-ready-for-qa

#2750 PROD-773 Fatar error when Clearing default data from BuddyBoss Tools
  src/bp-core/bp-core-tools-default-data.php
Labels: status-needs-review

#3344 Zoom datetime picker UI went wrong when Tutor LMS Pro activated - Fixed
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-core/compatibility/class-bb-tutor-pro-helpers.php
Labels: status-needs-qa, t3-needs-review
