Repository buddyboss/buddyboss-platform, pull requests merged in 2022-02, with the labels that each got.

#3283 PROD-1808 - Fix: Email Customizer in Dashboard shows random Moderation markup
  src/bp-core/bp-core-customizer-email.php
Labels: status-in-progress

#3151 PROD-699 #3124 - Fix: Preview link is not working when no any keystroke or only using right-click to paste the URL
  src/bp-activity/bp-activity-filters.php
  src/bp-core/classes/class-bp-embed.php
Labels: status-needs-qa

#3289 PROD-1857 fix - offload media php error
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: bug, status-needs-review, feature-media, feature-documents, feature-video, integration-compatible

#3196 PROD-712#3088 Fix Video upload progress bar showing 100% and still it does not allow post update due to confusion
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
Labels: status-changes-requested, priority-medium, merged-in-dev, t3-ready-for-release

#3242 PROD-1146 PROD-661 #3241 - Update styling for Profile Completion Widget for Theme 2.0
  src/bp-templates/bp-nouveau/buddypress/members/single/profile/widget.php
  src/bp-templates/bp-nouveau/common-styles/_bp_user_profile.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/languages/buddyboss.pot
Labels: feature-enhancement, status-in-progress, priority-medium, feature, epic-bb-theme-2-0

#2794 PROD-762 #2793 - fix: Cannot translate the Profile Photo and Cover Photo on Elementor Profile Completion widget
  src/bp-core/admin/bp-core-admin-tools.php
  src/bp-xprofile/bp-xprofile-filters.php
Labels: status-changes-requested, priority-low, merged-in-dev, t3-inprogress

#3173 PROD-698 #3126 - Fix: Links preview incorrect when we assign link to some strings.
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: feature-activity-feeds, status-needs-qa

#2912 PROD-778 #2696-fix-Title showing wrong if Rank Math SEO activated
  src/bp-core/compatibility/bp-rankmath-plugin-helpers.php
Labels: priority-low, needs-final-review, t3-needs-review

#3280 PROD-1799 Added order by parameter as id and include
  src/bp-activity/bp-activity-functions.php
  src/bp-activity/classes/class-bp-activity-activity.php
  src/bp-core/bp-core-functions.php
  src/bp-core/classes/class-bp-invitation.php
  src/bp-core/classes/class-bp-user-query.php
  src/bp-document/classes/class-bp-document.php
  src/bp-groups/classes/class-bp-groups-group.php
  src/bp-media/classes/class-bp-media.php
  src/bp-notifications/classes/class-bp-notifications-notification.php
  src/bp-video/classes/class-bp-video.php
Labels: status-in-progress
