Repository buddyboss/buddyboss-platform, pull requests merged in 2022-06, with the labels that each got.

#2962 PROD-742 Activity link preview issue during privacy update - Fixed
  src/bp-activity/bp-activity-filters.php
Labels: needs-final-review, t3-needs-review

#3181 PROD-693 #3140 - Fix: Activity post auto-refresh in activity page even if activity auto-refresh setting disabled
  src/bp-activity/bp-activity-filters.php
Labels: status-needs-qa

#3069 PROD-750 #2877 - Fix: Delete & Select all icons shows up when there is no video
  src/bp-templates/bp-nouveau/common-styles/_bp_video.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
Labels: bug, status-in-progress, priority-medium, feature-video

#2849 PROD-860#2116 - fix - gif play issue in private message
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
Labels: bug, t3-inprogress

#2399 PROD-844 - Fix #2243 : Past events not showing in search results
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
  src/bp-search/classes/class-bp-search-posts.php
  src/bp-search/classes/class-bp-search-types.php
  src/bp-search/classes/class-bp-search.php
Labels: bug, status-needs-review

#2983 PROD-744 Fix 2903 Issue with youtube preview whenever link has space at the end
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
Labels: needs-final-review, t3-needs-review

#3122 PROD-700 Fix #3121 Fixed the validation message,
  src/bp-templates/bp-nouveau/includes/activity/ajax.php
Labels: bug, status-needs-review, priority-medium

#2910 PROD-758 #2812 - Fix: Repeater > Repeater > Profile type showing the value instead off field text.
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.js
  src/bp-templates/bp-nouveau/js/buddypress-xprofile.min.js
Labels: needs-final-review, t3-needs-review

#2940 PROD-907 - #1594 - Fix reply notification redirects to the main comments instead of the exact reply
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/languages/buddyboss.pot
Labels: bug, needs-final-review, t3-needs-review

#2782 PROD-765 fix/2780 > Profile date field in repeater > empty value auto converts to date January 1970
  src/bp-xprofile/bp-xprofile-repeaters.php
Labels: bug, status-needs-qa

#3025 PROD-914 #1492 - Fix: Sort Group Types Alphabetically
  src/bp-templates/bp-nouveau/buddypress/common/filters/group-filters.php
Labels: status-needs-qa, merged-in-dev

#2923 PROD-759 Activity URL search with non ascii characters - issue fixed
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/languages/buddyboss.pot
Labels: status-needs-qa, t3-needs-review

#3054 PROD-722 Fix - Emojis are not fully shown on the site using a mobile device
  src/bp-core/js/emojionearea-edited.js
  src/bp-forums/templates/default/js/common.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
Labels: bug, status-needs-qa, priority-medium, requires-theme-update

#2135 PROD-859 Fixed Forum discussion Alignment Left or Right doesn't work when RTL language used
  src/bp-templates/bp-nouveau/common-styles/_bp_forums.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: bug, status-needs-qa, priority-medium

#2302 PROD-850Fixed # 2188 : Group URL doesn't work in email sent to admin
  src/bp-groups/bp-groups-notifications.php
Labels: bug, status-needs-review, feature-social-groups

#2886 PROD-812 #2456 - Fix: Messages > Default content &nbsp; enters when in messages user sent only image,doc or GIF.
  src/bp-document/bp-document-filters.php
  src/bp-media/bp-media-filters.php
  src/bp-messages/bp-messages-filters.php
  src/bp-messages/bp-messages-functions.php
  src/bp-messages/classes/class-bp-messages-box-template.php
  src/bp-templates/bp-nouveau/includes/groups/ajax.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-video/bp-video-filters.php
Labels: status-needs-review, status-changes-requested, t3-needs-review

#2763 PROD-862 Subscription automatically unsubscribes after editing a single Discussion in backend - Fixed
  src/bp-forums/topics/functions.php
Labels: needs-final-review, t3-needs-review
