Repository buddyboss/buddyboss-platform, pull requests merged in 2022-04, with the labels that each got.

#3023 PROD-927 #1306 - Fix: Add a confirmation alert before deleting a Profile Filed
  src/bp-xprofile/admin/js/admin.js
  src/bp-xprofile/admin/js/admin.min.js
  src/bp-xprofile/bp-xprofile-admin.php
  src/bp-xprofile/bp-xprofile-cssjs.php
Labels: status-needs-qa, merged-in-dev

#2864 PROD-753 Fix - Copy Paste error in replies and comments of the activity feed
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
Labels: bug, status-needs-qa, priority-medium, merged-in-dev

#2576 PROD-813 Fixed My groups link on a member profile page.
  src/bp-groups/bp-groups-filters.php
Labels: bug, status-needs-qa

#3286 Changed user suggestion list value to use user_nicename
  src/bp-groups/bp-groups-admin.php
  src/bp-groups/classes/class-bp-groups-member-suggestions.php
Labels: needs-final-review

#2633 PROD-816 Fix : The target attribute in Paragraph Text field is being removed after saving
  src/bp-xprofile/bp-xprofile-filters.php
Labels: bug, status-needs-review

#2982 PROD-794 Subforum topic search issue on mariadb 10
  src/bp-search/classes/class-bp-search-bbpress-forums-topics.php
Labels: priority-medium, needs-final-review, t3-needs-review

#2913 PROD-905 PROD-782 PROD-756 Fix #2818 Latest Activity widget: shows all the updates from non-connections and followers
  src/bp-templates/bp-nouveau/includes/activity/widgets.php
Labels: needs-final-review, t3-needs-review
