Repository buddyboss/buddyboss-platform, pull requests merged in 2022-05, with the labels that each got.

#3401 [PROD-2425] bp_before_member_header_meta hook multiple triggering fixed
  src/bp-templates/bp-nouveau/buddypress/members/single/cover-image-header.php
  src/bp-templates/bp-nouveau/buddypress/members/single/member-header.php
Labels: status-needs-qa, t3-needs-review

#3400 PROD-2405 - Fixed Profile headers > Social networks option is not showing if profile type is disabled
  src/bp-members/bp-members-admin.php
  src/bp-templates/bp-nouveau/buddypress/members/single/cover-image-header.php
  src/bp-templates/bp-nouveau/buddypress/members/single/member-header.php
Labels: status-needs-qa, t3-needs-review

#3370 @mention in forum > No suggestion shows after typing @ - Fixed
  src/bp-members/bp-members-filters.php
Labels: status-needs-qa, t3-needs-review

#3110 PROD-706 #3109 - Admin names should be display in message header section
  src/bp-templates/bp-nouveau/buddypress/common/js-templates/messages/parts/bp-messages-single-header.php
  src/bp-templates/bp-nouveau/includes/messages/ajax.php
Labels: bug, feature-private-messaging

#3457 PROD-2692 Renamed bp_nouveau_get_member_meta filter to bb_get_member_joined_date
  src/bp-templates/bp-nouveau/includes/members/template-tags.php
Labels: status-needs-review, t3-needs-review

#3456 Fatal error when blocking members when Member Connections component is disabled - Fixed
  src/bp-moderation/bp-moderation-filters.php
Labels: t3-needs-review

#3138 PROD-694 Performance improved - activity loading time reduced when multiple attached document
  src/bp-document/bp-document-functions.php
Labels: feature-documents, needs-final-review, t3-needs-review

#3034 PROD-725 Group type shortcode empty space at titlebar - fixed
  src/bp-groups/bp-groups-functions.php
Labels: needs-final-review, t3-needs-review

#1996 PROD-897 Fix/1735
  src/bp-forums/members.php
Labels: bug, priority-medium

#2718 PROD-820 The GIF comment is being deleted when the owner edit that activity post
  src/bp-media/bp-media-filters.php
Labels: bug, status-needs-review

#3346 Topic is not searchable if it has photos attached - Fixed
  src/bp-search/classes/class-bp-search-bbpress.php
Labels: status-needs-qa, t3-needs-review

#3420 Space Occupied when downloading folders - Fixed
  src/bp-templates/bp-nouveau/includes/document/functions.php
Labels: status-needs-qa
