Repository buddyboss/buddyboss-platform, pull requests merged in 2022-01, with the labels that each got.

#3146 PROD-718 #3066 - fix: Text format is being removed when pasting it in compose message or activity
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: priority-medium, status-ready-for-release, merged-in-dev, SP10

#2930 PROD-728 Link Preview of Publicly added url is redirected to Login Screen
  src/bp-core/bp-core-catchuri.php
Labels: bug, priority-medium, status-ready-for-release, merged-in-dev, SP10

#3049 PROD-721 Fix - Few strings are not translatable
  src/bp-templates/bp-nouveau/buddypress/document/document-create-folder.php
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/media/functions.php
  src/bp-templates/bp-nouveau/includes/video/functions.php
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-media.js
  src/bp-templates/bp-nouveau/js/buddypress-media.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
  src/languages/buddyboss.pot
Labels: bug, priority-medium, status-ready-for-release, SP10

#3068 PROD-717 Fix - Edit Profile type -> Search related setting should be available only if Network search is enabled
  src/bp-core/admin/bp-core-admin-functions.php
  src/bp-core/admin/css/common-rtl.css
  src/bp-core/admin/css/common-rtl.min.css
  src/bp-core/admin/css/common.css
  src/bp-core/admin/css/common.min.css
  src/bp-core/admin/sass/common.scss
Labels: bug, priority-medium, status-ready-for-release, merged-in-dev, SP10

#3008 PROD-731 Fix - 404 error for "video-js-rtl.min.css" when using RTL site language
  src/bp-core/css/vendor/video-js-rtl.css
  src/bp-core/css/vendor/video-js-rtl.min.css
Labels: bug, priority-medium, status-ready-for-release, SP10

#3129 PROD-697 Fix Changing group avatar also changing the user avatar on the header for time being
  src/bp-core/js/avatar.js
  src/bp-core/js/avatar.min.js
  src/languages/buddyboss.pot
Labels: bug, feature-social-groups, priority-medium, status-ready-for-release, SP10

#3218 PROD-670 #3217 - Fixed PHP warnings and notices
  src/bp-integrations/learndash/bp-learndash-filters.php
Labels: bug, status-ready-for-release, SP10, t3-ready-for-release

#3225 PROD-666 #3224 - Fix export personal data doesn't display profile type in downloaded file
  src/bp-xprofile/classes/class-bp-xprofile-field-type-member-types.php
Labels: bug, status-ready-for-release, SP10, t3-ready-for-release

#3272 API Enhancement and Fixes for 1.8.5
  src/bp-document/classes/class-bp-rest-document-endpoint.php
  src/bp-media/classes/class-bp-rest-media-endpoint.php
  src/bp-members/classes/class-bp-rest-signup-endpoint.php
  src/bp-video/classes/class-bp-rest-video-endpoint.php
Labels: status-ready-for-release, merged-in-dev

#2907 PROD-766 Fix #2776 Notification issue > Wrong name displayed when the user reply to reply in the discussion
  src/bp-forums/notifications.php
Labels: priority-medium, status-ready-for-release, merged-in-dev, requires-app-native-update, SP10, t3-ready-for-release

#3011 PROD-743 #2906 - Fix: Generating video thumbnail stuck at loading
  src/bp-templates/bp-nouveau/includes/video/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-video.js
  src/bp-templates/bp-nouveau/js/buddypress-video.min.js
Labels: priority-medium, status-ready-for-release, merged-in-dev, SP10, t3-ready-for-release

#2354 PROD-829 Fixed #2346 - Searching with ampersand character is not working
  src/bp-groups/classes/class-bp-groups-group.php
  src/bp-search/classes/class-bp-search-activities.php
  src/bp-search/classes/class-bp-search-groups.php
Labels: status-needs-qa, priority-medium, merged-in-dev, SP10, t3-ready-for-qa

#3180 PROD-719 Fix Video thumbnail issue with portrait video
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_video.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-video/bp-video-functions.php
  src/languages/buddyboss.pot
Labels: bug, priority-high, status-needs-qa
