Repository buddyboss/buddyboss-platform, pull requests merged in 2022-12, with the labels that each got.

#2344 PROD-830 Forum list widget parent forum ID issue - Fixed
  src/bp-forums/common/widgets.php
Labels: bug, status-needs-qa

#2909 PROD-918 #1437 - Fix PHP Error: Display name format conflict
  src/bp-core/bp-core-template.php
Labels: needs-final-review, t3-needs-review

#2961 PROD-736 Fix the wrong translation issue for comment
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/includes/activity/functions.php
  src/bp-templates/bp-nouveau/includes/activity/template-tags.php
  src/languages/buddyboss.pot
Labels: status-needs-qa, t3-ready-for-qa

#2995 PROD-883 Fix 1870 Condition added to prevent from duplicated first char with CJK IME
  src/bp-core/js/vendor/medium-editor.js
  src/bp-core/js/vendor/medium-editor.min.js
Labels: needs-final-review, t3-needs-review

#2977 PROD-839 Fix 2287 Spammed Discussion Content with documents are removed and unable to recover after unspam
  src/bp-forums/activity.php
Labels: needs-final-review, t3-needs-review
