Repository buddyboss/buddyboss-platform, pull requests merged in 2022-08, with the labels that each got.

#3299 PROD-1974 layout issue with geodirectory - Fixed
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: needs-final-review

#3352 Right-click paste adds duplicate text in private message - Fixed
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
Labels: status-needs-qa, t3-needs-review

#2887 PROD-781 Symbolic links settings changed when updating the activity settings - issue fixed
  src/bp-core/admin/bp-core-admin-schema.php
Labels: needs-final-review, t3-needs-review

#3596 PROD-3239 : Notification Badge Shows Same Count After 'Mark All as Read'
  src/bp-notifications/classes/class-bp-notifications-notification.php
Labels: bug

#3564 PROD-3196 Fix baclslashes for notification description with quotation…
  src/bp-notifications/bp-notifications-template.php
Labels: status-needs-review, t3-needs-review
