Repository buddyboss/buddyboss-platform, pull requests merged in 2023-01, with the labels that each got.

#2870 PROD-752 A Warning shows when gavatar is enabled and user trying to update the profile - Fixed
  src/bp-core/admin/bp-core-admin-tools.php
  src/bp-core/deprecated/buddyboss/1.6.4.php
  src/bp-xprofile/bp-xprofile-functions.php
Labels: needs-final-review, t3-needs-review

#2790 PROD-948 Fix - Group message email notification is not sending when the organizer has an Instructor role
  src/bp-core/compatibility/bp-incompatible-plugins-helper.php
Labels: status-needs-qa, t3-ready-for-qa

#1582 PROD-922 #1356 - Fixed rtl issue for profile completion widget counter
  src/bp-templates/bp-nouveau/common-styles/_bp_user_profile.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress.css
Labels: bug, status-needs-qa, priority-medium

#1238 PROD-934 I can not visualize code in plugin editor in the RTL language mode
  src/bp-templates/bp-nouveau/buddypress-functions.php
Labels: status-changes-requested

#1852 PROD-923 - Backslash (\) in the forum post is not showing in Activity Feed
  src/bp-forums/activity.php
Labels: bug, status-needs-review, priority-medium

#2830 PROD-872 #1988 - Fix The text area for posting photos or documents is no longer visible when forum component is disabled
  src/bp-templates/bp-nouveau/buddypress/document/document-uploader.php
  src/bp-templates/bp-nouveau/buddypress/document/uploader.php
  src/bp-templates/bp-nouveau/buddypress/media/uploader.php
  src/bp-templates/bp-nouveau/buddypress/video/uploader.php
Labels: blocked, t3-backlog

#2841 PROD-865#2064 - Fix Forum List Widgets Disregarding (Parent Forum ID) on the widget query
  src/bp-forums/common/widgets.php
Labels: needs-final-review, t3-needs-review

#3021 PROD-739 #2947 - Fix: Profile edit > Field set issue in saving
  src/bp-xprofile/bp-xprofile-repeaters.php
  src/bp-xprofile/screens/edit.php
Labels: needs-final-review, t3-needs-review
