Repository buddyboss/buddyboss-platform, pull requests merged in 2023-05, with the labels that each got.

#3923 PROD-5155 PROD-3770 Fixed group forum reply link
  src/bp-forums/groups.php
Labels: status-needs-review

#3944 PROD-5140 Fixed discussion replies pagination count issues
  src/bp-forums/replies/functions.php
Labels: status-needs-review

#3595 PROD-3373 Fixed link clickable in CPT activity post comment
  src/bp-activity/bp-activity-filters.php
Labels: status-needs-review, t3-needs-review

#3953 PROD-5142 Fix default notification preferences
  src/bp-core/bp-core-functions.php
  src/bp-members/bp-members-functions.php
  src/bp-notifications/bp-notifications-functions.php
Labels: t3-inprogress

#3133 PROD-716 Fix slug accent issue
  src/bp-forums/admin/functions.php
Labels: status-changes-requested, t3-inprogress

#3123 PROD-734 #2988 Fixed mentioning in blog post comments doesn't send notifications
  src/bp-activity/bp-activity-filters.php
  src/bp-activity/bp-activity-notifications.php
  src/bp-activity/classes/class-bp-activity-notification.php
  src/bp-blogs/bp-blogs-activity.php
  src/bp-blogs/bp-blogs-filters.php
  src/bp-core/bp-core-actions.php
  src/bp-core/bp-core-functions.php
  src/bp-core/classes/class-bb-post-notification.php
  src/bp-members/classes/class-bp-members-mentions-notification.php
  src/bp-notifications/bp-notifications-functions.php
Labels: status-changes-requested, priority-low, merged-in-dev, t3-ready-for-release

#2871 PROD-842 #2263 - Fix- bp_search_query_results issue
  src/bp-search/classes/class-bp-search.php
Labels: needs-final-review, t3-needs-review
