Repository buddyboss/buddyboss-platform, pull requests merged in 2023-04, with the labels that each got.

#2365 PROD-895 PROD-2512 Fixed #1787 Comma operator issues with members count
  src/bp-core/bp-core-filters.php
  src/bp-friends/bp-friends-template.php
  src/bp-friends/classes/class-bp-friends-component.php
  src/bp-groups/bp-groups-filters.php
  src/bp-media/classes/class-bp-media-component.php
  src/bp-templates/bp-nouveau/includes/ajax.php
  src/bp-templates/bp-nouveau/includes/friends/ajax.php
  src/bp-templates/bp-nouveau/includes/media/ajax.php
  src/bp-templates/bp-nouveau/includes/video/ajax.php
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
  src/bp-video/classes/class-bp-video-component.php
Labels: bug, status-in-progress, status-changes-requested, priority-medium

#3902 Fixed profile fields update issue for member with non-selectable profile type
  src/bp-xprofile/classes/class-bp-xprofile-field-type-member-types.php
  src/bp-xprofile/screens/edit.php
Labels: status-needs-review

#3383 PROD-2351 - Performance issue of function bp_xprofile_pg_user_query_search - Fixed
  src/bp-xprofile/bp-xprofile-functions.php
Labels: status-needs-qa, t3-needs-review

#2992 PROD-740 #2921 - Fix: New User Role Assignment doesn't stick upon initial User creation
  src/bp-members/bp-members-filters.php
  src/bp-members/bp-members-functions.php
Labels: status-changes-requested, priority-low, merged-in-dev, t3-ready-for-release

#3149 PROD-692 Fix - Safari - Video thumb not saving
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.js
Labels: bug, status-in-progress, priority-medium
