Repository buddyboss/buddyboss-platform, pull requests merged in 2023-02, with the labels that each got.

#3427 PROD-2426 PROD-4311 Fixed activity feed media layout for small device
  src/bp-templates/bp-nouveau/common-styles/_bp_activity_entries.scss
  src/bp-templates/bp-nouveau/common-styles/_bp_media.scss
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
Labels: status-needs-review, t3-needs-review

#3766 PROD-4352 Fix orderby for group types filter
  src/bp-templates/bp-nouveau/buddypress/common/filters/group-filters.php
Labels: status-needs-review, t3-needs-review

#3827 Fixed fatal error on BB group update
  src/bp-integrations/learndash/buddypress/Sync.php
  src/bp-integrations/learndash/learndash/Admin.php
  src/bp-integrations/learndash/learndash/Sync.php
  src/bp-integrations/learndash/library/SyncGenerator.php
Labels: status-needs-review

#3285 PROD-1824 - Reply button label on Email does not fit when translated to a longer string
  src/bp-core/classes/class-bp-email-tokens.php
Labels: needs-final-review

#3277 PROD-684 fixed #3177 autocomplete suggestions position changed to make it near the searchbox
  src/bp-templates/bp-nouveau/js/buddypress-search.js
  src/bp-templates/bp-nouveau/js/buddypress-search.min.js
Labels: needs-final-review

#3202 PROD-682 Fix Medium JS with some text like the placeholders are hardcoded and its not translatable
  src/bp-forums/templates/default/js/editor.js
  src/bp-templates/bp-nouveau/buddypress-functions.php
  src/bp-templates/bp-nouveau/css/buddypress-rtl.css
  src/bp-templates/bp-nouveau/css/buddypress-rtl.min.css
  src/bp-templates/bp-nouveau/css/buddypress.css
  src/bp-templates/bp-nouveau/css/buddypress.min.css
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
  src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.min.js
  src/bp-templates/bp-nouveau/js/buddypress-activity.min.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-group-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.js
  src/bp-templates/bp-nouveau/js/buddypress-messages.min.js
  src/bp-templates/bp-nouveau/js/buddypress-nouveau.min.js
Labels: bug, status-needs-qa, priority-medium

#3832 Fixed terms table prefix name
  src/bp-search/classes/class-bp-search-posts.php
Labels: status-needs-review
